config/app.php

This allows app provider to override anything registered in Laravel's `ServiceProvider`s.

Switch the order of app providers

---

config/app.php

The default `key` in `app.php` config *must* match the `.env.example` app key on a new project - otherwise `artisan key:generate` is actually silently failing.
This is because `key:generate` is searching `.env.example` for `YourSecretKey!!!` when it doesnt exist (because `.env.example` currently has `SomeRandomString` as the default).
As a side note - the current `key:generate` command still leaves the default key in `app.php` unchanged. Is that also a bug - or a design intention to force people to use manually change it? Might be worth running a one-off command to set another random key there as well (separate from the `.env.example` key)?

[Bug] Composer create-project key:generate currently broken

---

.gitignore

Seems sensible if Laravel's going to push Elixir.
A person unfamiliar with the node ecosystem should be able to use Elixir with ease, however I don't feel they should necessarily know up-front that they should add node_modules to their global `.gitignore` file.

[5.0] Add "node_modules" to .gitignore

---

resources/views/welcome.blade.php

When using https://example.com, the welcome page design looks off due to fetching the Lato font on http://.
Ref: https://github.com/laravel/framework/issues/7159
**Update:** Using no protocol i.e `//`

Use no protocol to fetch Lato font

---

phpunit.xml

We should set the queue driver to be `sync` when testing by default. Makes sense along side the other testing defaults like cache and session etc

Have logical default for Queue Driver when testing

---

resources/views/welcome.blade.php

Otherwise the header output will be something like "localhost:port"

Added <title> tag

---

resources/views/errors/503.blade.php

Fixes issues when loading font in HTTPS.

Use relative href on 503 font path

---

package.json

Was merged already some time ago  in https://github.com/laravel/laravel/commit/75393db929a43a6b56a85bdc65a4f607f77efcd8 but was lost a merge after.

Get rid of npm warning: "npm WARN package.json @ No repository field."

---

resources/views/auth/login.blade.php

Doing so negates the need inline styling, as Bootstrap has a `btn-link` class which works with grouped buttons.

Remove inline styling, add class to link

---

resources/views/auth/login.blade.php
resources/views/auth/password.blade.php
resources/views/auth/register.blade.php
resources/views/auth/reset.blade.php

Third time lucky? ;)
> Added "for" attribute in auth related example views for both usability/accessibility reasons, and testability - regarding Codeception's fillField method, which will not work without the relation set by "for" (at least when the input is not nested within its label. Using "for" attribute is the cleaner method, imo).

Use "for" attribute on labels in auth views

---

app/Providers/AppServiceProvider.php
public/index.php
tests/ExampleTest.php
tests/TestCase.php

This converts AppServiceProvider to spaces since it wasn't and removes a few empty lines after class declarations.
This is a re-PR of #3314 due to it being locked.
@GrahamCampbell #3314 was for the develop branch, so is this one.  Sorry I didn't put it in the title to make it more clear.
Ping @OzanKurt, @pespantelis.  Yes, you're correct, the master branch is not PSR-2 but the develop branch is.

[develop] Fix indent format.

---

config/services.php

Small change. Stripe API has a secret and public key. Both should be stored in the config.

Minor update to Stripe config

---

storage/.gitignore

The `laravel.log` already ignored in `storage/logs/.gitignore` file.

Delete unnecessary .gitignore file

---

app/Providers/RouteServiceProvider.php

Kindly check if my assumption is correct? In relation to this issue, http://stackoverflow.com/questions/28251154/laravel-5-0-dev-defining-global-patterns-is-not-working/29567578#29567578 and https://laracasts.com/discuss/channels/general-discussion/route-global-pattern-in-routeserviceprovider-not-working-in-laravel-5?page=1
Not really an issue, it's just probably creating some confusions for others
or this could be a different issue/bug
thanks!

Defining global patterns before parent boot function call

---

readme.md

Make the security contact visible on the repository itself, instead of just the documentation.

Add security contact to readme

---

app/Http/Middleware/VerifyCsrfToken.php

Commit https://github.com/laravel/laravel/commit/89f568156f59e374d98523f18493672ab380c42e made the Closure namespace import redundant in VerifyCsrfToken

Remove redundant Closure namespace import in VerifyCsrfToken

---

resources/lang/en/validation.php

Turns out there is no validation message for the `string` rule.
Now there is :)

Add validation message for string rule

---

composer.json

Clear compiled can fail after update it should be run before update.

Fix occasional clear-compiled failure after update

---

database/seeds/DatabaseSeeder.php

Leaving models unguarded can cause all kinds of havoc if someone uses seeds in their tests.
Best to default to reguard after doing the seeds.

Enable model guarding after doing seeds

---

composer.json

post-create-project-cmd is executed only after post-install-cmd and this
could cause issue on the first installation (via composer
create-project) where environment is not prepared hence `php artisan
optimize` would generate `compiled.php`.
1. `post-install-cmd` execute `php artisan optimize` while `.env` doesn't exist (env=production & debug=false).
2. `post-create-project-cmd` execute copying `.env.example` and generate key.
1. `post-root-package-cmd` copy `.env.example` to `.env` so we can have (env=local & debug=true).
2. `post-install-cmd` execute `php artisan optimize` with correct `.env`.
3. `post-create-project-cmd` generate key.
Refer to <https://getcomposer.org/doc/articles/scripts.md#command-events>
Signed-off-by: crynobone <crynobone@gmail.com>

[5.1] Move copying .env.example to post-root-package-install

---

config/database.php

In the framework database configuration, the 'mysql' and 'pgsql' connections default to charset UTF-8. The 'sqlsrv' default connection doesn't specify a default charset.
In many typical default installations of FreeTDS / dblib on Linux, the charset is inadvertently set to something other than UTF-8. As UTF-8 is the preferred default in the vast majority of use cases, it makes sense to hardcode this charset in the 'sqlsrv' connection as well. This avoids having to create a custom database configuration just to set the charset ( see #3417 )

Set default charset for sqlsrv driver to utf8

---

composer.json

Prevent people from using unstable package by default. Also affects what composer chooses.
Example: `composer require symfony/dom-crawler` will get:
> Using version ^3.0@dev for symfony/dom-crawler
With `stable`, they get the correct version (`^2.7`)
As far as I know, previous versions of Laravel always shipped with `stable` as default, don't know why that has changed?
Fixes #3419 and #3414

Set minimum stability to stable

---

public/.htaccess

Folders that exist have a redirect loop when visiting them. This is because Apache redirects to trailing slash for folders and the current rule is removing it, Apache then adds a trailing slash again.

Fix redirect loop .htaccess

---

config/database.php

According to the docs, the sqlite database should be located within the "database" folder.

Replace storage_path with database_path helper

---

config/queue.php

Use same DB_CONNECTION enviroment variable for queue.failed.database config

Change default value for queue.failed.database

---

resources/lang/en/validation.php

[The replacer](https://github.com/laravel/framework/pull/10766/files#diff-38fd116b7c7b8ac1bdd8362250d04d57R1982) uses `:values` rather than `:value`.

required_unless lang line fix

---

app/Http/Middleware/RedirectIfAuthenticated.php

The route **/home** doesn’t exist in a default Laravel application, whereas **/** does.

Change redirect when authenticated

---

config/app.php

I have not seen this alias be very functional since it quotes were removed from the home page of laravel.

[5.1] Remove alias Inspiring

---

app/Console/Kernel.php

The class is unnessarily fully quantified and is an warning that is also flagged up in popular IDE's such as PHPStorm. It is also arguably bad practice as it can lead to problems if directories are moved in the future.

Remove unnecessary fully quantified name

---

config/auth.php

Should be _separate_ not _seperate_ :)

Typo in docs

---

app/Console/Kernel.php

If the purpose of the command is to demonstrate, does not become nescessário leave it enabled by default.

Disable demonstration command

---

app/Http/Middleware/Authenticate.php

Currently, any unauthorized API requests that pass through the `auth` middleware get a redirect to the login page. Adding the `wantsJson` flag to the conditional corrects this behavior.

[5.2] Don't return a login page to a JSON request

---

.env.example

This change was made for those developing on Windows and noticed ridiculous response times (1 second) even locally. Windows performs a DNS lookup for 'localhost' which always takes 1 second. I thought I would save the few Windows people (like myself) some time with troubleshooting slow installs of redis (this is where I first noticed it).
[http://stackoverflow.com/questions/14076403/redis-connection-slow-from-php](http://stackoverflow.com/questions/14076403/redis-connection-slow-from-php)

.env.example - Changed localhost to 127.0.0.1

---

config/cache.php

Had an issue where my employer has an application that they deploy to different targets. Memcached needed to be configurable on a per-environment basis (i.e. staging, beta, production) so having hard-coded options wasn’t ideal. Would be great if these were configurable via environment variables out of the box.

[5.2] Make Memcached options configurable.

---

database/factories/ModelFactory.php

Faker’s `email()` method can accidentally generate email addresses. This ensures “safe” addresses are only ever generated by the factory, to avoid spamming actual mailboxes if mail was sent in a loop etc.

Use safeEmail() in user factory instead

---

database/migrations/2014_10_12_000000_create_users_table.php

Laravel hashes passwords with `bcrypt()` which returns a 60 character hash. In order to future-proof the user table for advances in password hashing technology, we should allow the max amount of characters for the database column.
See php.net's documentation on [`password_hash()`](http://php.net/password_hash):
> It is recommended to store the result in a database column that can expand beyond 60 characters (255 characters would be a good choice).
PS: This PR was done in front of the [Laravel Chicago PHP User Group](http://www.meetup.com/laravel-chicago/events/228116711/). We love Laravel! :)

Fix password column for future hashing

---

resources/lang/en/validation.php

The message after validation failure will look like:
```
The products.*.id field has a duplicate value.
```

Add language line to the validation "distinct" rule

---

resources/lang/en/validation.php

The message will look like:
```
The users.2.branch_id field does not exist in branches.*.id.
```
It depends on https://github.com/laravel/framework/pull/12565 for the replacer to replace `:other` with the other field.

Add language line for the in_array validation rule

---

app/Http/Controllers/Auth/AuthController.php

When you're filling the registration form and you leave the password empty:
you're going to get an error that both passwords do not match
whereas it makes sense to show the "your password must be at least 6 characters long" error first
or else a user might have a `confirmed` 5 characters password first and then he sees the `min:6` error

Fixed order of password validation in registration

---

composer.json

Can't rely on being able to run php artisan, before updating. See https://github.com/composer/composer/issues/5066
> Before, running install without a lock file did an install that was almost an update, but still ran the pre/post-install-cmd scripts. Now we normalized it to actually run an update and fire pre/post-update-cmd, because that's what it is doing. If you have a lock file though it will run install as before.
When installing without lockfile, Composer now behaves as upgrade. It also executes the `pre-upgrade-cmd` instead of `pre-install-cmd`. Behaviour with composer.lock available is not changed.
With the latest composer version, doing a fresh install will fail because the vendor files are not yet present.

Remove pre-update-cmd

---

storage/framework/.gitignore

```php
// From: Illuminate\Console\Scheduling\CallbackEvent
/**
* Run the given event.
*
* @param  \Illuminate\Contracts\Container\Container  $container
* @return mixed
*
* @throws \Exception
*/
public function run(Container $container)
{
if ($this->description) {
touch($this->mutexPath());
}
...
/**
* Get the mutex path for the scheduled command.
*
* @return string
*/
protected function mutexPath()
{
return storage_path('framework/schedule-'.sha1($this->description));
}
```

Ignore schedule files

---

config/database.php

Having this configurable by ENV allows for easily running tests in memory by adding this to the phpunit.xml:
```
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
```

[5.2] Allow for setting sqlite database via env

---

composer.json

Use ComposerScripts to avoid loading any configuration/compiled files.
Should probably be done **after** a new (laravel/framework) version is tagged, to avoid problems with non-existing class..

[5.2] Use ComposerScripts

---

app/Http/Middleware/Authenticate.php

I think if you use the `auth` middleware with a particular driver, you'd expect calls to `Auth::user()` and `$request->user()` to return the user from that driver.

Set the default driver from the Authenticate middleware

---

phpunit.xml

We'll need to update the docs to let people know about this.

Fixed up the phpunit config

---

config/database.php

When "strict" mode is set to false it allows the database to ignore significant errors rather than abort and return the error to PHP. An example would be trying to save a string in an INT field...instead of throwing an error, the save completes successfully and simply inserts a 0 in the field.
This means that the default setting allows for data loss with no notification, which seems like a really bad thing. The default should be to the safest setting, which could then be reconfigured by the developer if necessary.

[5.3] Enabled MySQL "strict" mode by default

---

config/database.php

The commit https://github.com/laravel/framework/commit/586bffa1d758e09114821b694b5e800cc9bbfb5f added support for sslmode in PostgresConnector.php and sslmode has been around since postgres version 9.1 (2011). 
This change makes it possible to specify sslmode from the config file and also serves as documentation to other developers so they don't have to dive deep into the code to figure out that it's posible to set this option.
The posible values for sslmode are: disable, allow, prefer, require, verify-ca, verify-full
The default value is "prefer".
http://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-PROTECTION

[5.3] Add "sslmode" setting for PostgreSQL connection

---

app/Http/Controllers/Auth/PasswordController.php

guestMiddleware() defined on ResetsPasswords trait
This change is required to fix issue laravel/framework#13383
Depends on pull request laravel/framework#13384

[5.2] Get guest middleware using guestMiddleware() method in ResetsPasswords

---

config/services.php

Add the Mandrill array in config.services to access the secret key from the `.env`.

Add missing Mandrill secret keys in config.services

---

app/Http/Kernel.php

[It's being moved](https://github.com/laravel/framework/pull/13767) into the `Auth` namespace.

[5.3] Update `can` middleware to new namespace

---

tests/TestCase.php

I can't see a use case for TestCase needing to be directly instantiated, so it makes sense to convert this to abstract.
This also solves the issue when running tests in a given directory / suite, PHPUnit will no longer complain about no tests being present in TestCase.

Make TestCase abstract

---

config/broadcasting.php
config/cache.php

While `config/mail.php`, `config/queue.php`, `config/session.php` have all available drivers listed in them, `config/broadcasting.php` and `config/cache.php` do not.
This PR makes sure that all config files have their drivers listed and follow same convention. 🌵

List supported drives in cache and broadcasting configs

---

database/migrations/2014_10_12_100000_create_password_resets_table.php

Prevents MySQL assigning default CURRENT_TIMESTAMP
Related issue: laravel/framework#11518

Make password_resets.created_at nullable

---

config/auth.php

Signed-off-by: crynobone <crynobone@gmail.com>

[5.3] Password broker would always use notifications::email view.

---

resources/lang/en/validation.php

I was using the [file validation rule](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Validation/Validator.php#L1541) and found out there is no validation translation for this rule. So.. here it is!

Add language line for file validation rule

---

phpunit.xml

Because routes file now outside app folder by default. We can remove that section

Remove removed routes file

---

.env.example

Since we now have a default config as:
```php
'key' => env('APP_KEY'),
```
And during the `artisan key:generate` command as following:
```php
file_put_contents($this->laravel->environmentFilePath(), str_replace(
'APP_KEY='.$this->laravel['config']['app.key'],
'APP_KEY='.$key,
file_get_contents($this->laravel->environmentFilePath())
));
```
The generated app key would be generated with suffix of `SomeRandomString` because it's not the original key, the original key is either `null` (or `''`).
Signed-off-by: crynobone <crynobone@gmail.com>

[5.2] Remove default APP_KEY value

---

config/app.php

when i started, i ended up putting all package specific service providers just at the bottom of the application service providers. But when making a route group like domain.com/{keyword}, the packages that are registering its own url's, not work anymore (like now when i installed the translations manager from barryvdh). When putting them above the app specific, everything works. So just give it to the user as a default place?

give newbees a package service providers section, preventing adding after application

---

.env.example

When the developer copies `.env.example` to `.env` they are unlikely to add quotes to the values in `.env`. When the developer needs to set the value of an environment variable to a value containing a
space, as none of the existing values in `.env` are quoted, the developer is unlikely to wrap this new value with spaces in quotes. This will result in an error, as the vlucas/phpdotenv library throws
an error when setting an environment variable to a value with a space.
Quote all default environment variables by default, reducing the likelihood of the developer ever receiving the error relating to environment variables needing to be quoted when they contain spaces.
The current default values in `.env.example` don't contain any spaces, so this commit will make no difference out of the box; …

Wrap .env.example variable values in quotes

---

app/Exceptions/Handler.php

This is a totally extraneous PR that just fixes a few things that we commonly see with our usage of Laravel and phpmd.
Php Mess Detector ([phpmd](https://phpmd.org)) takes a given PHP source code base and looks for several potential problems within that source. Including possible bugs, suboptimal code, overcomplicated expressions, unused parameters, methods, properties, etc.
This PR fixes a few minor things that phpmd complains about with every new project we make. Specifically this replaces variable names that are too short ($e) and removes an extraneous `else` statement.

Compliance with commonly used phpmd rules

---

resources/assets/js/bootstrap.js

the word "framework" was missing in the docblock above Vue in `resources/js/bootstrap.js`.
I managed to make the docblock fit Laravel's style by changing around some of the wording while keeping the general message the same.

Fix missing word in docblock

---

.gitignore

If you open a (laravel) project in phpstorm, it places an `.idea` folder in the project root. This contains project-specific ide settings. You usually don't want to include such files in a git repo.

GitIgnore PHPStorm's config directory

---

database/factories/ModelFactory.php

Use a precomputed hash of the word "secret" instead of using `bcrypt` directly. Since `bcrypt` is intentionally slow, it can really slow down test suites in large applications that use factories to generate models in many tests.
Here's a reference point from a user who saw their test suite get 5x faster thanks to this change 👀
https://github.com/laravel/laravel/pull/3456#issuecomment-216460694

Use precomputed hash instead of bcrypt in ModelFactory

---

app/Providers/RouteServiceProvider.php

Having this middleware will enforce protection over all routes defined in `api.php`, however not all API routes needs to be protected.
I suggest we remove that middleware and allow developers to assign middleware as they see fit.
I know they can always remove it manually from the ServiceProvider, but I think it shouldn't exist by default from the beginning ¯\_(ツ)_/¯

Remove default auth:api middleware

---

routes/console.php

The description of a command is shown via `php artisan` so the default command `inspire` should have description as well.

Adding description for default inspire command

---

resources/lang/en/validation.php

Changing the order of the validation.php to respect the alphabetical order, the new mimetypes is in the wrong place

Lang Alphabetical Order

---

app/Providers/RouteServiceProvider.php

When developing SPAs, it makes sense to have a 'catchall' route and then handle the routing with javascript (like with [`vue-router`](http://router.vuejs.org/en/)). It would also make sense to have some API endpoints for the SPA to talk to.
However, if you were to add a catchall to the `web.php` routes and then some API endpoints to the `api.php` routes, the `api.php` routes would be ignored as the catchall takes precedence, since `web.php` routes are mapped first.
This PR proposes that we map API routes first, so that those routes take priority before a catchall / similar route is set by `web.php`.
Here is the proposal in `internals`: https://github.com/laravel/internals/issues/187

[5.3] Map API routes before Web routes

---

package.json

There seems to be a problem with `laravel-elixir@6.0.0-9` and Vue 2. The newest version fixes it.
Reference Issue - laravel/passport#131

Updates laravel-elixir version for vue 2 compatibility

---

.gitignore

These files should not end up in source control IMO. And even though Passport is a separate package it is a first-party one and the base Laravel install should be "prepared" for it.
What do you guys think?

Ignore Passport-generated OAuth keys

---

resources/views/welcome.blade.php

Normally I am completely against adding too many things to the `welcome.blade.php` view.
I say this because this file is usually one of the first things to be deleted when starting a new application.
However, building a simple application may not need you to delete this file. That's where this PR comes in.
Instead of always displaying the 'Login' and 'Register' links on the top right of the welcome screen, when the user is signed in, a link to the 'Home' page is displayed.
This can easily be used to determine if you are currently signed in (without having to click either link and be redirected to the 'Home' page).
**tl;dr**
Adds a 'Home' link to the `welcome.blade.php` file. You can easily see if you are signed in.
(Edit: Woah. This is the 4,000th pull request 😃)
(Edit 2: *sigh* I just …

Add home link to welcome page

---

app/Http/Controllers/Auth/ResetPasswordController.php

Considering this is already present in the register & login controllers, I don't see why we shouldn't have it already present in the reset password controller, after all it basically logs you in after resetting.

Add redirectTo attribute to the reset password controller

---

gulpfile.js

When using arrow functions, parentheses are recommended if the function takes a single argument and uses curly braces. See section 8.4 of Airbnb's JavaScript style guide, one of the most popular.

Added recommended parentheses

---

config/database.php

In https://github.com/laravel/laravel/pull/3641 was decided to use `127.0.0.1` instead of `localhost` to avoid DNS lookups
This change is to maintain consistency between `.env` and `database.php`

Changes localhost to 127.0.0.1 in database config

---

config/database.php

Follow the same logic of #4045 for Redis.

Use the IP instead of DNS in redis host

---

config/database.php

fix: `AUTH failed: ERR Client sent AUTH, but no password is set [tcp://127.0.0.1:6379]`
According to predix release log: https://github.com/nrk/predis/releases/tag/v1.1.1

Support predis v1.1.1

---

config/database.php

```
[Predis\Connection\ConnectionException]
`AUTH` failed: ERR Client sent AUTH, but no password is set [tcp://127.0.0.1:6379]
```

Fix redis password `AUTH` failed

---

resources/assets/js/bootstrap.js

It seems the library doesn't send the `X-Requested-With: XMLHttpRequest` header by default, if it's not present `$request->ajax()` always returns false.

Make axios compatible with Request::ajax()

---

composer.json

It's much easier to search for packages in the `composer.json` file when they're sorted by default. Having this on a fresh Laravel install from the beginning would be nice :)

[5.3] Sort Composer packages by default

---

config/queue.php

Normally, words that start with vowels (like "unified") are preceded by "an" instead of "a."  However, "unified" is an exception to the rule.
Source: https://www.a-or-an.com/a_an/unified

Fixed a typo in a block comment queue.php

---

package.json

Salutations and good day. This PR (pull request) will bring great glory to the Laravel™ framework by upgrading its Laravel Mix dependency from the old version 0.4.0 release up to the current 0.5.0 iteration.
I trust that you will merge this ethical PR (pull request) in a prompt manner, so that the users of your framework may enjoy the reputable Laravel Mix repository - version 0.5.0, not 0.4.0 (see above) - in their new projects.

Bump Mix dependency

---

package.json

Windows tries to execute the JS file directly.

Ensure cross-env gets executed by node

---

.gitignore

Following https://github.com/laravel/framework/pull/17571, I was correctly pointed that the small proposition should be made over here. Here's a copy / past of my message, for clarity's sake.
---
When you run `npm run hmr`, a `hot` file is created to the public folder for the `mix()` helper to know if it has to server from the webpack server or not. This file does not go away until we run `npm run dev` (or `watch`). 
True, if we use `npm run production` in our production server it goes away too, but in case we don't make it go away in development, I don't think it's necessary to version it.

Remove the hot file from versionning

---

bootstrap/autoload.php

Redundant check removed since compiled class file generation was removed
https://github.com/laravel/framework/commit/09964cc8c04674ec710af02794f774308a5c92ca#diff-7b18a52eceff5eb716c1de268e98d55dL870

Remove redundant check from bootstrap/autoload.php

---

composer.json

To execute PHP scripts, you can use `@php` which will automatically resolve to whatever
php process is currently being used.
See https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts
for more information.

Append '@' to let composer resolve PHP executable

---

resources/assets/js/bootstrap.js

Axios doesn't automatically send the `X-CSRF-TOKEN` that [the passport token guard](https://github.com/laravel/passport/blob/f2a8af3a48adac02288779f59de95f46fef69b7a/src/Guards/TokenGuard.php#L204) is looking for.
See https://github.com/laravel/passport/issues/256 and https://github.com/laravel/docs/pull/3045

Make Axios automatically send `X-CSRF-TOKEN` in the header

---

resources/views/welcome.blade.php

Add App locale as default lang in the app.php config file instead of 'en' of 'lang' attribute in the main view.

Add App locale as default value of 'lang' attribute

---

composer.json

As demonstrated in laravel/framework#17699 it is possible to have phpunit being installed with a lower than `5.7.0`, which doesn't work at all on 5.4 due to the changes with PHPUnit namespaced class.

Laravel 5.4 explicitly require phpunit 5.7.0+

---

app/Exceptions/Handler.php

Change hard-coded '/login' param to named route 'login'.
Adding a bit of flexibility to work with translations w/o need change Handler class:
`
Route::get('entrar', 'CustomController@showLoginForm')->name('login'); `

Change hard-coded '/login' param to named route

---

resources/lang/en/validation.php

`filled` isn't really required. It just implies that it needs a value.

[5.4] Update description of filled rule

---

package.json

Resending in #4166 because it *is* actually the correct behavior. The only thing what was missing is that since you're directly using the binary it *needs* to be added to the devDependencies which will make it available in the `.bin` directory (even if you use Yarn). You can drop the full path like @kentcdodds reasoned. 
This way #4162 won't be an issue anymore in the future.
/cc @kentcdodds @jankal @willvincent @eklundkristoffer @pagchen

Fix cross-env binary

---

package.json

Update laravel-elixir-vue-2 to 0.3.0 for a out of the box [Object.assign buble-loader polyfill](https://github.com/vuejs/laravel-elixir-vue-2/commit/336e76e3e93d5f023a4219b8ecc2fdeb435d983f#diff-168726dbe96b3ce427e7fedce31bb0bc) (especially useful when working with vuex)

update laravel-elixir-vue-2 to 0.3.0

---

config/database.php

For the mysql driver only (as this only applies to mysql) add the "unix_socket" configuration parameter and corresponding environment variable.
added in #4039, but with the wrong key name. The `unix_socket` parameter IS supported by the [`MysqlConnector`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Connectors/MySqlConnector.php#L108) class, and there is currently no way to modify it via environment variables.

Adds unix_socket to config/database.php for consistency

---

database/migrations/2014_10_12_100000_create_password_resets_table.php

No one runs query with `where token = ?`, the query does not mean anything because tokens are hashed before storage.

unindex token

---

.gitattributes

Some projects can present JS as the primary language, even clearly being a Laravel/PHP project. With this, that problem can be avoided.

The .js files should be vendored too

---

readme.md

I was browsing the Patrons - and I noticed "British Software Development" leads to a non-existent url?
I think it should be `.co` rather than `.com`? That website looks valid?

Possible URL fix?

---

.gitignore

I figure since PHPStorm has been considered, that I'd add the vagrant virtual machine directory to prevent unnecessary committing of large disk images and state. Especially useful for those using Homestead.

Add vagrant virtual machine directory to git ignore list.

---

package.json

It trips me up each time that `npm run dev` exists but `npm run prod` does not. This serves to fix that case, as well as providing consistency in both directions `dev`/`development` and `prod`/`production`.
[Source](https://twitter.com/michaeldyrynda/status/846507021251690497)

Provide consistency with NPM scripts

---

package.json

`$npm_package_scripts_development` and alike commands are not supported under Windows, as they can only be used in the `%npm_package_scripts_development%` format. Therefore, `npm run dev` currently gives an error.
To support every OS and both short and long names, I think it's inevitable to have redundant commands.

NPM scripts should support Windows

---

package.json

`dev` and `prod` are just aliases, so this allows to just defer them to their counterparts.
`watch-poll` just adds one extra argument so the special option `--` allows to pass it to the `watch` script.

DRY some npm scripts

---

.env.example
config/app.php

This PR makes the application name configurable via an environment variable. By default, this is set to "Laravel" as per the current configuration in the `app.php` config file.
When developing applications with Laravel, I am often putting a version onto a staging server as well as a production server. By making the app name configurable, when I get `Mailables` sent to me (which, by default use the app name) I can see more easily whether the e-mail has come from the staging server or the production server.
It can also make it easier to identify which version of an application is being viewed in a browser (for example configuring the local development version with `Local` at the end can avoid mistakes when there are multiple tabs open with local, staging and production versions of the …

Make app name configurable in environment file

---

resources/assets/js/bootstrap.js

This change ensures the default "Accept" header specified by axios is retained.
Previously, checking `$request->wantsJson()` on a request made from axios would return false since the "Accept: application/json... (etc)" header was omitted.
This change uses the format specified in the axios docs here https://github.com/mzabriskie/axios#global-axios-defaults

Add to axios defaults instead of overwriting them

---

artisan
phpunit.xml

https://github.com/laravel/laravel/pull/4226 removes `bootstrap/autoload.php` and breaks `artisan`. This PR fixes `artisan` to work.

Fix break from #4226

---

.gitignore

When an NPM run fails, is created a npm-debug.log file. This file can be ignored and should not be published on a Git based repository.

Ignore the npm debug log

---

resources/views/welcome.blade.php

doctype uppercase to lowercase

---

config/queue.php

Although it wont affect anything - it might lead to confusion if people think it is still an option.
It can be added back if the feature is re-added at a later stage.

Revert Queue Prefix

---

config/database.php

Since the doc says that the Laravel supports SQL Server out of the box, makes sense add it, out of the box.

Add sqlsrv as group connection

---

config/database.php

Most installations won't work without it.

Added port to sqlsrv settings

---

resources/lang/en/validation.php

The `ipv4` and `ipv6` validation rules [documented here](https://laravel.com/docs/5.4/validation) aren't present in `resources/lang/en/validaton.php`.

Add missing IPv4/IPv6 validation messages

---

phpunit.xml

Not a huge deal, but this
```
unit --testsuite Feature
```
is substantially easier to type than this
```
unit --testsuite "Feature Tests"
```
I find the former description informative enough and it's not out of the question that you will need to run specific test suite via command line or as part of a CI routine.

Simplify test suite names

---

webpack.mix.js

Note that I left your dang `const` as it is, even though it's stupid. `let` for life. 💃💃💃💃

Simplify mix require

---

resources/assets/sass/app.scss

Sass compilers can sometimes be weird if import urls like this aren't quoted. They'll spit out junk like
```
Error: Encountered invalid @import syntax.
```
Anyways, pretty common practice to use quotes for all imports. I mean, seriously, how much more do you want me to write for a dang PR that adds a pair of quotes? I've got work to do, gah.

Add quotes

---

package.json

This will make sure version 1.0 of Larvel Mix is pulled in

Require Laravel Mix 1.0

---

app/Http/Middleware/TrustProxies.php

It appears that the http_foundation Request object has deprecated `HEADER_CLIENT_*` as of 3.3 and will be removed in 4.0
This PR updates the header keys in the TrustProxies middleware class to use the corrected constant from the http_foundation library

Fix to TrustProxies

---

config/session.php

Derives session.cookie from SESSION_COOKIE, falling back to (snake_cased) APP_NAME . '_session', falling back to 'laravel_session' (current) in order to make it less discoverable, thereby (slightly) reducing threat vector.

:wrench: Reduce discoverability of session cookie name.

---

.gitignore

Like the npm error log, this file can also be ignored.
[See also](https://stackoverflow.com/questions/42592168/should-i-add-yarn-error-log-to-my-gitignore-file)

Ignore the Yarn error log

---

composer.json

The list of migrations in your app can grow massively and these currently automatically get included in your composer classmap. Migrations are intended to be run as a one-time thing and are already automatically [`required`](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Migrations/Migrator.php#L436) so this PR avoids unnecessarily adding the migrations to your composer file.

Remove migrations from autoload classmap

---

public/.htaccess

Previously redirection to remove trailing slashes would fail if Laravel was not installed in the root directory. REGEX moved from RewriteRule to RewriteCond fixes this.

Fixed trailing slash redirection for subdirectory installs.

---

resources/assets/sass/app.scss

This fixes the annoying error shown on the import line
Cannot resolve directory 'node_modules' less... (Strg+F1) 
This inspection checks references to files and directories.

Fixes "Cannot resolve directory'" in PhpStorm

---

package.json

Minor style issue more than anything.
If using `php artisan preset` it will use PHP's `JSON_PRETTY_PRINT` to rewrite the file (https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/Presets/Preset.php#L44). `JSON_PRETTY_PRINT` uses four spaces for indentation, causing the entire file contents to be altered upon a diff.
Rather than adding logic to change the indentation after executing `json_encode()` in `Illuminate\Foundation\Console\Presets\Preset`, it seems easier to just fix the default indentation in `package.json`. NPM doesn't seem to change the spacing at all, so this seems like a happy medium.

Change indent for package.json from 2 to 4 spaces

---

bootstrap/autoload.php

When you run `phpunit` it requires `/vendor/autoload.php` by itself.
Because `/app/bootstrap.php` is set as `bootstrap` in `phpunit.xml` then `autoload.php` is loaded twice.
You can verify this by adding
```php
echo "COMPOSER\n";
```
in your `/vendor/autoload.php`
This PR prevents second loading of this file.
Before
After
On not testing run Laravel requires this file as usual.

require_once /vendor/autoload.php

---

config/database.php

Suppose we have the following set up in .env:
```
DB_CONNECTION=sqlite
DB_DATABASE=database/mydb.sqlite
```
Doing a `php artisan migrate` will work on specified database.
The problem is that if the app is run with `php artisan serve`, it will give a database `database/mydb.sqlite` does not exist error.
To fix this, why not change this
```php
'database' => env('DB_DATABASE', database_path('database.sqlite')),
```
to this?
```php
'database' => database_path(env('DB_DATABASE', 'database.sqlite')),
```
So that db file path is in now returned correctly by _database_path_ helper.

Use database_path helper for sqlite database filename specified in .env

---

public/.htaccess

If you open the `/css`, `/js`, or any other folder on the default server, you can see the list of files in the directory.
The `-Indexes` option forbids viewing directory files via the web interface.

Added "-Indexes" option

---

composer.json

Match `mockery/mockery` with [laravel/framework](https://github.com/laravel/framework/blob/5.5/composer.json#L78)

[5.5] Match mockery/mockery with laravel/framework

---

package.json

Mix's build output gets quite noisy, particularly in static build output (CI/CD, Jenkins, etc.) and makes the Forge deployment log in particular quiet slow. I've seen a few beach balls tracking down how to limit this output.

Don't show progress for production run command

---

config/filesystems.php

Aids those users that are using the AWS CLI tools, by matching the `filesystems.disks.s3`
configuration values with those that would be set in a user's native environment already.
AWS Documentation [reference](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html).
Resolves laravel/internals#778

Update AWS environment variable defaults

---

config/filesystems.php

Add the `url` property to the configuration of the `s3` driver. This requires the laravel/framework#22037 pull-request to be merged.

Support custom URLs for AWS storage

---

public/.htaccess

If you open the /css, /js, or any other folder on the default server, you can see the list of files in the directory.
The -Indexes option forbids viewing directory files via the web interface.
(#4422 for 5.5 branch)

[5.4] Added "-Indexes" option

---

app/Http/Middleware/TrustProxies.php
composer.json

Trusted proxy now either trusts the `Forwarded` header, or all `X-Forwarded-*` headers to determine the correct client info when a proxy is used.
Symfony 4 no longer supports using custom headers. This takes away an unfortunate feature, but simplifies the package a bit.

Trusted proxy to version 4.0 for Laravel 5.6

---

app/Http/Kernel.php

Integrates laravel/framework#22389.
Maybe `cache-headers` would be a better name?

[5.6] Add the SetCacheHeaders middleware

---

tests/CreatesApplication.php

This is an idea that was originally suggested by @jrmadsen67 and mentioned by @daylerees here https://driesvints.com/blog/two-tips-to-speedup-your-laravel-tests/
Adding this to some legacy testing suites reduced my testing time down by 34% - which is fairly significant for one line of code.
Not everyone will get this level of performance gain. It will largely depend if you are seeding new users (and there using `bcrypt`) and/or if you are using database transactions etc.
But adding this to the app framework seems like a sensible default for testing, as there is no benefit is wasting time computing harder hashes during tests - even if it is only a handful of times.

Reduce Hash computations during tests

---

composer.json

This PR proposes the addition of the package [Collision](https://github.com/nunomaduro/collision) as **dev** dependency of every Laravel app. Collision is an detailed & intuitive error handler framework for PHP **console** applications, and includes an adapter/service-provider for **Laravel**.
The package project is [https://github.com/nunomaduro/collision](https://github.com/nunomaduro/collision) and bellow is an screenshot example.
Those are the Collision **dependencies**:
```json
"require": {
"php": "^7.1",
"filp/whoops": "^2.1.4",
"symfony/console": "~2.8|~3.3|~4.0"
}
```
Concerning the integration Laravel, If the exception implements the  `Symfony\Component\Console\Exception\ExceptionInterface`, [Collision](https://github.com/nunomaduro/collision) still uses the default …

[5.6] Adds nunomaduro/collision on composer require-dev

---

database/factories/UserFactory.php

Using a hard coded hash is good for performance, but it might be very frustrating for a new user to figure out what the actual password value is

Add comment with the value of the hashed password

---

resources/assets/js/bootstrap.js

Details in [laravel/docs PR 3932](https://github.com/laravel/docs/pull/3932)

Update Echo options for pusher in bootstrap.js

---

app/Http/Controllers/Auth/RegisterController.php

Replace the bcrypt helper function of the create method from RegisterController with Hash::make() in order to use Argon2 driver if set in config/hashing.php.

Add Argon2 support to create method in RegisterController

---

resources/assets/sass/_variables.scss

This variables was in bootstrap 3 but actually does not exist in version 4.

Remove sass variables which does not exist in bootstrap 4

---

composer.json

Reverts laravel/laravel#4574
Sorry, but I dont think this was given the correct level of discussion regarding the huge unintended side effects this PR is going to have.
Essentially we are now permanently faking composer to pretend that every Laravel install is running on PHP `7.1.3` out of the box.
This is going to artifically limit everyone as packages start increasing their dependencies to PHP `>=7.1.4`, because the default Laravel install will *never* get those packages. And it will be a **silent** failure - because composer will just grab the older versions without complaining.
Of course - people are free to edit their `composer.json` with the right version. But then they need to do this. every. single. time.
Plus - when you do `composer create-project laravel/laravel blog` - that …

Revert "[5.6] Use composer platform config"

---

composer.json

The `thanks` package is not needed to develop kickass Laravel apps.

[5.6] Remove unnecessary package

---

composer.json

The only semantic change here is that the PHP version is now bounded in the same way it is for the framework repo.

[5.6] Use semver caret operator

---

phpunit.xml

Set the array driver as a default for testing to avoid sending emails with smtp the default driver which slows down tests

[5.6] Set MAIL_DRIVER to array in phpunit.xml

---

config/queue.php

The description here has bothered me for a while, because it is kind of misleading.
The `QUEUE_DRIVER` environment variable perhaps also needs changing to `QUEUE_CONNECTION`, but I'm not sure if that is just too engrained in legacy systems now? I can change that on this PR if you agree, and also the matching `QUEUE_DRIVER=sync` in `.env.example`.

The default queue "driver" is actually a "connection"

---

package.json

The watch command is the same as the development command, just with a watch flag.

Simplify the npm watch command

---

app/Exceptions/Handler.php

remove comment suggesting to send reports to bug trackers in this method.
with the new improvements to the logging system, I think we no longer want to encourage this method of handling errors.

[5.6] Update handler

---

config/services.php

The region used by SES was hard-coded into the config file, when all other values were set as environment variables. Tweaked to keep the region consistent with other config options

Add SES_REGION to local environment file

---

config/hashing.php
phpunit.xml
tests/CreatesApplication.php

This allows to maintain the `tests/CreatesApplication` clean and uses a hashing option dedicated solely for that purpose.

[5.6] Set bcrypt rounds using the hashing config

---

config/cache.php
config/database.php

The cache is often flushed (eg. on deployments). When using redis for cache and other databases, this will have the side-effect to also clear sessions/queues/horizon metrics etc.
See also:
https://github.com/laravel/framework/issues/20655
https://github.com/laravel/horizon/issues/72
https://github.com/laravel/horizon/issues/171
https://stackoverflow.com/questions/45620872/how-to-create-another-redis-server-instance-on-same-server-managed-by-laravel-f/46869372#46869372
You could argue that it's safer / more performant to use a seperate database (or better, instance) for each task, but I think cache is the only one that get's regularly flushed, right?

[5.6] Use seperate cache database for Redis

---

phpunit.xml

Unit tests usually run faster and provide more fine-granular feedback if something is broken. If some small part of the application is broken, it may easily cause all the feature tests to fail, while not providing useful feedback.

[5.6] Switch execution order of testsuites, unit tests first

---

composer.json

This PR adds the https://github.com/beyondcode/laravel-dump-server package as a dev-dependency.

Add beyondcode/laravel-dump-server as dev dependency

---

app/Http/Kernel.php
app/Http/Middleware/CheckForMaintenanceMode.php

Integrating the new except-URI functionality for the maintenance mode (see: PR #24740 in `laravel/framework`) as boilerplate middleware.

[5.6] Adding boilerplate maintenance middleware with excepted URIs array

---

.gitignore

PHPUnit version 7.3 adds a new argument `--cache-result` which allows you to do awesome things like re-run test failures using a command like:
`phpunit --cache-result --order-by=defects --stop-on-defect`
The cache file is stored as `.phpunit.result.cache`
I believe PHPUnit 8 will have caching on by default, so this file will start popping up in everyone's project quickly.

Add .phpunit.result.cache to the .gitignore

---

package.json

This PR updates Lodash to `^4.17.5` from `^4.17.4`. I recently installed a new Laravel App and I got an email from GitHub within a few hours about a severe security vulnerability with Lodash `4.17.4`:
via [https://nvd.nist.gov/vuln/detail/CVE-2018-3721](https://nvd.nist.gov/vuln/detail/CVE-2018-3721):
> Lodash node module before 4.17.5 suffers from a Modification of Assumed-Immutable Data (MAID) vulnerability via defaultsDeep, merge, and mergeWith functions, which allows a malicious user to modify the prototype of "Object" via __proto__, causing the addition or modification of an existing property that will exist on all objects.

Upgrade Lodash (Security Vulnerability)

---

config/session.php

In the spirit of JMac & LaravelShift I've extracted 2 session variables to the environment file. Not 'just because' but that one is able to set SESSION_DRIVER to redis, but unable to set a connection without touching the core session config file.

Extract 2 core configurations for sessions to environment

---

composer.json

After the PR https://github.com/laravel/laravel/pull/4600, we are defaulting to the "Caret Version Range".

[5.7] Use semver caret operator for laravel-dump-server

---

webpack.mix.js

`mix` isn't re-assigned (and shouldn't be) so `const` is more appropriate.

[5.7] Define mix as const

---

resources/lang/en/pagination.php

https://github.com/laravel/framework/commit/d3c0a369057d0b6ebf29b5f51c903b1a85e3e09b broke the links of simple pagination (https://github.com/laravel/framework/issues/25430):
{{ User::simplePaginate()->links() }}
> &amp;laquo; Previous
> Next &amp;raquo;

[5.6] Fix pagination translation

---

phpunit.xml

Pretty strait forward. Looks like phpunit.xml was overlooked when changing the QUEUE_DRIVER env var to QUEUE_CONNECTION.

Updated QUEUE_DRIVER env var to QUEUE_CONNECTION in phpunit.xml

---

config/services.php

Counterpart to https://github.com/laravel/framework/pull/25010
Necessary for EU users, as they use api.eu.mailgun.net instead of api.mailgun.net

Add missing Mailgun 'endpoint' option

---

app/User.php

The base class Illuminate\Foundation\Auth\User already uses the MustVerifyEmail trait.

Removing unnecessary use from User Model

---

app/Http/Controllers/Auth/VerificationController.php

As noted by @arxeiss in issue https://github.com/laravel/framework/issues/25503
All controllers in `App\Http\Controllers\Auth` extend `App\Http\Controllers\Controller`, except for `VerificationController` which was extending `Illuminate\Routing\Controller`.
This makes all the controllers consistent.

[5.7] Update VerificationController

---

app/Http/Kernel.php

The `Authenticate` middleware is intended to be called in a specific order before applying developer-listed middleware. In 5.7, it was changed to `App\Http\Middleware\Authenticate` but the priority still lists it as living under `Illuminate\Auth\Middleware\Authenticate`.
This proposed fix moves that priority array to `App\Http\Kernel` and changes the reference to the userland class.

[5.7] Update HttpKernel to use Authenticate middleware under App namespace

---

storage/framework/cache/data/.gitignore

Keeps the `/storage/framework/cache/data/` directory, in order to allow the filesystem cache to function properly.
Resolves https://github.com/laravel/framework/issues/25451

[5.7] Persist the /storage/framework/cache/data directory

---

config/logging.php

*Why consider this?*
Daily logging makes an application more "production ready" out of the box. I know developers are considered to set this config, but for many new or inexperienced devs this isn't common knowledge.
Sticking to daily by default makes more sense to me:
- Way easier of getting an overview of what happened in a chronological order.
- No chance of consuming lots of disk space by huge logs.
I understand this is also partly a personal preference, so I'd welcome any feedback or constructive criticism why this should remain as is or changed to something different.

[5.7] Set logs to daily by default

---

bootstrap/app.php

This PR ensures that the app base path is stream-safe instead of the [potential unexpected behavior of using `realpath()`](https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#phar-incompatible-realpath-usage).

[5.7] Make app path stream safe

---

config/app.php

As per [that PR](https://github.com/laravel/framework/pull/17895) and [the documentation](https://laravel.com/docs/5.6/database-testing#writing-factories), I wanted to make sure this was present in the `app/config.php` out of the box.
It's a great thing and I'm sure people will be happy to use it rather than overriding the singleton registration.

[5.7] Adding faker_locale default config value.

---

resources/lang/en/pagination.php

#4744 adjusted the pagination translation after https://github.com/laravel/framework/commit/d3c0a369057d0b6ebf29b5f51c903b1a85e3e09b started escaping the output of  `@lang` calls. Now that `d3c0a36` got reverted, we can revert this fix.

[5.7] Revert #4744

---

database/factories/UserFactory.php

The new requirement for user password is of 8 characters, as set by #4794 and laravel/framework#25957.
This pr updates the UserFactory password to `password`

[5.8] Update UserFactory password in line with #4794

---

app/Http/Middleware/Authenticate.php

When calling api routes the Authenticate middleware attempts to redirect you to the login page. If you expect JSON back or don't have auth routes then you don't want this to happen. By re-using the logic from Laravel's exception handler on which format to output we can also determine wether to redirect the user to the login page or give them a JSON error response.

[5.7] Don't redirect for api calls

---

resources/views/welcome.blade.php

With Nunito, the 12px size with uppercase hase bad render (FF & Chrome).

Fix bad font size render on link

---

resources/js/bootstrap.js

Before this PR, running `php artisan preset none` and then running all Mix tasks `npm run production` would output an error:
`ERROR in ./resources/js/bootstrap.js`
`Module not found: Error: Can't resolve 'popper.js'`
This PR turns it into a warning keeping the same behaviour as when `bootstrap` and `jquery` modules are missing:
`WARNING in ./resources/js/bootstrap.js`
`Module not found: Error: Can't resolve 'popper.js'`

[5.7] Fix running mix tasks error

---

config/queue.php

It's common to have a redis queue name when having multiple queues/applications on the same instance. Default value is the same.

[5.7] use env value for redis queue name

---

config/database.php

This enables the sqlite `foreign_key_constraints` option that was introduced with laravel/framework#26298 for all new installs.
The env variable DB_FOREIGN_KEYS was added to make it easier to handle this in testing (e.g. via phpunit.xml).

introduce sqlite foreign_key_constraints config option

---

resources/js/app.js

Not sure if this is too magical, but Webpack has a feature called [require.context](https://webpack.js.org/guides/dependency-management/#require-context), which allows you to traverse a directory. Using this, we can automatically register all the Vue components in the `/js` directory. This happens at build time, so there is no performance implications.
Note, this will register Vue components in sub folders as well, so it's the developer's responsibility to avoid naming collisions, since the folder name isn't included in the component name (although it could be added if they wanted). I don't see this as an issue, in fact I like it since it allows organization of Vue files into folders, but it's good to be aware of.
Examples:
- `/js/components/ExampleComponent.vue` becomes …

Auto register Vue components

---

resources/js/app.js

Love this new addition, but don't often use the full Lodash library. By using `pop()` instead of `_.last()`, everything will continue to work without Lodash being pulled in from `bootstrap.js`.

[5.7] Remove lodash dependency when auto registering Vue components

---

readme.md

Cyber-Duck is an official sponsor of Laravel- [Laravel Partners](https://laravel.com/partners)
Added an entry to list Cyber-Duck under Laravel Sponsors.

Add Cyber-Duck as a Sponsor

---

app/Http/Middleware/RedirectIfAuthenticated.php

Same as #3685 , this will allows to
```php
Route::get('foo', 'Foo@foo')->middleware('guest:web,api');
```

[5.8] Modify RedirectIfAuthenticated middleware to accept multiple guards

---

config/queue.php

This functionality was added in laravel/framework 9aa1706.

[5.8] Add beanstalk queue block_for config key

---

app/User.php

The default included migration for the users table includes a timestamp field for 'email_verified_at'.
However, it might be a convience if the User model (stub) interpretes this field as a Carbon instance instead of a plain date/time string.
It also serves as a nice way to show the attribute casting feature on models for someone new to Laravel

Attribute casting for 'email_verified_at' on User model stub (with explanation)

---

resources/views/welcome.blade.php

Remove the link MIME type "text/css" definition since its use is unnecessary according to the HTML5 specs: https://html.spec.whatwg.org/multipage/semantics.html#the-link-element.

[5.7] Remove unnecessary link type on "welcome" view

---

composer.json

**This PR needs to wait until laravel/framework has PHPUnit 8 support: https://github.com/laravel/framework/pull/27441**
Encourage people on 5.8 to use PHPUnit 8.

[5.8] Update to PHPUnit 8

---

phpunit.xml

Laravel 5.8 limits dotenv to only rely on $_SERVER and not $_ENV. See https://github.com/laravel/framework/pull/27462

[5.8] Use $_SERVER instead of $_ENV for phpunit.

---

database/migrations/2014_10_12_000000_create_users_table.php

All new generated migrations will be using `bigIncrements`
see https://github.com/laravel/framework/pull/26472
https://github.com/laravel/framework/blob/8107fe1d3769fdef35a8ccb85d9ff0d942380394/src/Illuminate/Database/Migrations/stubs/create.stub#L17

[5.8] use bigIncrements by default

---

config/app.php

Now that array and string helpers have been removed, we should add aliases for `Arr` and `Str` to the default `config/app.php`, so that they can be easily used in views:
```blade
<h1>{{ Str::title($post->title) }}<h1>
```

[5.8] Add Arr and Str aliases by default

---

config/cache.php
config/queue.php
config/services.php

This PR replaces mentions of old `AWS_REGION` env variable in config files with new `AWS_DEFAULT_REGION`.

[5.8] Use correct env name for AWS region from env.example

---

composer.json

This PR upgrades the collision dependency from v2 to v3 as mentioned here: https://twitter.com/enunomaduro/status/1103775614849482753

[5.8] upgrade the collision dependency from v2 to v3

---

database/.gitignore

When SQLite is being used, journals appear as temporary files. However if the process that is using SQLite is terminated (Interrupting Dusk tests for example) before SQLite properly cleans after itself, you are left with said journal, which shouldn't be commited obvs.

Ignore SQLite journals

---

config/database.php

This PR prefixes the `redis` database connection by default to mitigate multiple sites on the same server potentially sharing the same queued jobs. It uses similar logic to that which is used for creating the cache prefix.

[5.8] Prefix redis database connection by default

---

config/cache.php
config/database.php

This PR adds an additional underscore to the end of the generated cache prefix and redis database prefix.
Addresses the relevant points regarding poorly named keys, mentioned by @fitztrev @ludo237 @gerardnll in https://github.com/laravel/laravel/pull/4982.

[5.8] Add underscores to cache and redis database prefixes

---

config/cache.php

This PR removes the underscore from the cache prefix, as cache prefixes automatically have a colon appended to them.
This change came from discussion here: https://github.com/laravel/laravel/pull/4986.

[5.8] Remove underscore from cache prefix

---

database/factories/UserFactory.php

Reorder the `@var` phpdoc block syntax by convention, see http://docs.phpdoc.org/references/phpdoc/tags/var.html

Reorder phpdoc block by syntax convention

---

.gitattributes

I noticed that this file was being included when i ran the `laravel new` command and even though some developers will run StyleCI, the purpose of this file seems more like it ensures the repository quality rather than providing an starting point for this service.
On the other hand, this are really good defaults so i'm open minded about this, just wanted to make sure this wasn't an oversight 😃

Exclude StyleCI config from exported files

---

app/Http/Middleware/TrustProxies.php

Trusted proxies example from the docs:
```
/**
* The trusted proxies for this application.
*
* @var array
*/
protected $proxies = '*';
```

[5.8] Fix type hint for case of trusting all proxies (string)

---

package.json

Update axios in package.json to ^0.19 so that I don't get security vulnerability notification emails from Github when I push to my laravel project repos even though "^0.18" covers 0.19 as well
See: https://nvd.nist.gov/vuln/detail/CVE-2019-10742
This PR is similar in nature to this: https://github.com/laravel/laravel/pull/4730 (not the same vulnerability, but the justification to update)

[5.8] Update axios package

---

.gitignore

When running Laravel Dusk tests, the application `.env` gets renamed to `.env.backup`, and is restored when the tests are done. However, if you abort the tests, the `.env.backup` still exists. Adding it to the gitignore could help prevent it from being accidentally committed.
Edit: i just noticed this was rejected before in https://github.com/laravel/laravel/pull/4411

Add .env.backup to gitignore

---

app/Http/Kernel.php

Noticed this when trying to do `php artisan down --allow=<ip>` if your behind Cloudflare / some other proxy it won't allow you to access site - this is because `TrustProxies` only kicks in *after* maintenance mode middleware.
It also makes sense to me to whitelist a request straight away as the first thing in the app before firing any subsequent middlewares.

[5.9] Move TrustProxies to highest priority - fixes maintenance mode ip whitelist if behind proxy e.g. Cloudflare

---

config/broadcasting.php

I was looking at source code pusher php library:
https://github.com/pusher/pusher-http-php/blob/60148190da064d662caeceee9a920592b5aae78e/src/Pusher.php#L107-L113
Seems both options are supported, but they are saying `encrypted` is deprecated.
Also, Laravel documentation is showing the `useTLS` instead of `encrypted`:
https://laravel.com/docs/5.8/broadcasting

[5.8] Update deprecated pusher option

---

package.json

Hello!
lodash in package.json - 4.17.5, but [CVE-2019-10744](https://github.com/lodash/lodash/pull/4336) affected versions (<4.17.13) of lodash are vulnerable to Prototype Pollution

[5.8] Fixed lodash version (CVE-2019-10744)

---

config/database.php

It was the only redis setting that wasn't overridable by an environment variable. It can help if you have multiple instances using the same `APP_NAME`, e.g. a staging instance

[5.8] Using environment variable to set redis prefix

---

phpunit.xml
tests/bootstrap.php

This PR introduces a PHPUnit  ~~watcher~~ bootstrap file that caches the config before the test suite runs for the first time, which in [my benchmarks](https://timacdonald.me/the-case-laravel-testcase/) reduces the boot time of the Kernel during a test run by ~50% without any additional work by the developer.
This will only really have an impact on a larger test suite, but personally I think it is a worthwhile thing to consider.
The benchmark test suite ended up with the following durations:
- Without caching: 9.15s
- With caching: 4.2s
Caching the config before a test run is good for a couple of reasons:
1. It's faster.
2. It is closer reflects what you use in production.
If, for example, you cache your routes in production but try deploy a sneaky closure route, your app is gonna blow up …

[6.0] Add PHPUnit bootstrap file to allow execution of console commands before a test run

---

resources/lang/en/passwords.php

This got removed in its related PR here: https://github.com/laravel/framework/pull/29480

[6.0] Remove deprecated language line

---

resources/js/bootstrap.js

In `bootstrap.js` we currently add a `X-CSRF-TOKEN` HTTP header (note the 'C') to the Axios instance that we instantiate, using the value of a `<meta>` tag added by the auth scaffolding. This is not necessary because [Axios already has similar functionality](https://github.com/axios/axios/blob/master/dist/axios.js#L1077) enabled by default where it will add a `X-XSRF-TOKEN` HTTP header (note the second 'X') using the value of the `XSRF-TOKEN` cookie.
On a current installation of Laravel, our Axios instance requests have both the `X-CSRF-TOKEN` and the `X-XSRF-TOKEN` HTTP headers. The only difference is the `X-CSRF-TOKEN` value is unencrypted, while the `X-XSRF-TOKEN` value is encrypted.
I believe we can safely remove the `X-CSRF-TOKEN` HTTP header configuration from `bootstrap.js` because …

[5.8] Remove unnecessary X-CSRF-TOKEN header from our Axios instance

---

config/database.php

Follow up for https://github.com/laravel/framework/pull/29688
It's best that we already start using `phpredis` as a default to discourage usage of Predis.
I'm not sure where `REDIS_CLUSTER` is set? Probably a native Redis option?

[6.0] Use phpredis as default Redis client

---

.editorconfig

The YAML docs generally recommends using .yaml as the preferred extension for YAML files - https://yaml.org/faq.html.
I've tweaked the .editorconfig to set both yaml and yml files to have the same indentation. Without this, *.yaml files default to 4 spaces.

[6.x] Allowing optional use of yml/yaml file extensions in .editorconfig

---

config/hashing.php

https://bugs.php.net/bug.php?id=78516
Argon2 requires at least 8KB
On PHP 7.4 memory 1024 will throw:
password_hash(): Memory cost is outside of allowed memory range

[6.x] According to PHP Bug 78516 Argon2 requires at least 8KB

---

config/hashing.php

Reverts laravel/laravel#5097. ~Laravel's hash manager should select the correct value to pass to PHP. The intended default is 1MB, across any PHP version.~ The bug will be fixed before PHP 7.4 is released.

Revert "[6.x] According to PHP Bug 78516 Argon2 requires at least 8KB"

---

config/logging.php

As proposed on https://github.com/laravel/ideas/issues/1806, this implementation ads a 'none' logging channel which outputs logs to nowhere by using Monolog's 'NullHandler' class.

[6.x] Add 'null' logging channel

---

app/Http/Controllers/Auth/ConfirmPasswordController.php
app/Http/Controllers/Auth/ForgotPasswordController.php
app/Http/Controllers/Auth/ResetPasswordController.php
app/Http/Kernel.php
config/auth.php
resources/lang/en/validation.php

These changes along with the new password confirmation functionality and the new password rule. See https://github.com/laravel/framework/pull/30214
I've also removed the "guest" middleware from the password reset controllers so users can reset their password while logged in. This was needed in combination with the new password confirmation screen. See https://github.com/laravel/ui/pull/34

[6.x] Password confirmation

---

composer.json

After https://github.com/laravel/laravel/pull/5129, the current application boilerplate within `laravel/laravel` does not work with the previous version of Laravel 6. Giving the error:
`Illuminate\Contracts\Container\BindingResolutionException Target class [Illuminate\Auth\Middleware\RequirePassword] does not exist.`
This pull request addresses that exact same issue, specifying that the current boilerplate only works with newer versions of the Framework.
> Note: Probably nobody will ever face this problem, just making my first contribution of the day. 🤗

[6.x] Fixes required version of the framework within `composer.json`

---

config/auth.php
resources/lang/en/passwords.php

Hello!
An attacker can use the password recovery function to spam the user's mailbox and / or overload the mail server.
This can be avoided by delaying the next attempt to use the password recovery function.
Also changes to laravel/framework are submited.
Thanks!
P.S. Test coverage to laravel/framework added.

[6.x] Waiting before retrying password reset

---

resources/js/bootstrap.js

The `encrypted` option for Pusher is deprecated and replaced with `forceTLS`.
This PR updates the example code in`bootstrap.js`.
See https://github.com/pusher/pusher-js/pull/293

[6.x] Rename `encrypted` to `forceTLS` for Pusher

---

composer.json

This pull request adds the next major version of Collision: `v4.0`.
Note that this version is not tagged yet, as discussed with @taylorotwell, I am waiting that my development dependencies to support Laravel 7 / Symfony 5 and I am also working in a redesign of the console exceptions.
Meanwhile, this is working using the composer branch alias feature proxying `^4.0` to `dev-next`.

[7.x] Bumps nunomaduro/collision dependency to 4.0

---

composer.json

To be merged when tinker v2 is ready. This can then make it into 7.x by merging `master` -> `develop` in the usual way.

[WIP] [6.x] Use laravel/tinker v2

---

phpunit.xml
tests/Unit/ExampleTest.php

Hey everyone. With this PR I want to propose a new dedicated Integration test directory and in-memory DB defaults to the default Laravel test suite. As someone who's worked quite a bit with different test suites over the past years I think I can say for myself I have quite some experience in this area and wanted to share some small things through this PR.
The first thing I want to change with this PR is to provide new defaults for the database that's being used when running the test suite of the app. **This is probably the very first thing I change for every single app I start working on.** All of my tests run in memory against a sqlite database which is pretty fast I must say. 
While it is true that the current default Laravel test suite doesn't requires a database to be set up, it is …

[6.x] Implement integration test and in-memory DB

---

app/Http/Controllers/Auth/ConfirmPasswordController.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/Auth/ResetPasswordController.php
app/Http/Controllers/Auth/VerificationController.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Providers/RouteServiceProvider.php

We were defining this path in six places (!).

[6.x] DRY up path to /home

---

config/session.php

The cookie functionality is built on the one from Symfony, which lacked support for "same-site: none" until a coupe of months ago.
In some cases, Chrome might block cookie access for both strict and lax, so would be imported to know that "none" is supported too.
⚠️ When using same-site: none, Chrome also needs secure to be set to true. Does this need to be mentioned as well?
Symfony PR: https://github.com/symfony/symfony/pull/31475

[6.x] Add "none" to supported same site options in session config

---

app/Http/Middleware/Authenticate.php

Updates return type doc block to be same as [parent one](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/Middleware/Authenticate.php#L90).

[6.x] Update redirectTo return type PHPDoc

---

config/logging.php

This adds a default emergency logger path to the logging config file.
---
Goes hand-in-hand with laravel/framework#30873.

[6.x] Allow configurable emergency logger

---

config/mail.php

I continually forget to set `MAIL_FROM_NAME` and IMHO it makes more sense to default to the app name vs. “Example”

[6.x] Default email from name to app name

---

app/Http/Kernel.php
app/Providers/AuthServiceProvider.php

This change adds the `AuthenticatesRequests` marker interface as the target of the `auth` middleware and binds that interface to the application's `Authenticate` middleware.
The purpose for this change is to allow us to remove the `middlewarePriority` middleware from the application's HTTP kernel. Even though the Foundation's HTTP Kernel contained a base priority, it was not possible to remove this here because we needed to have the Authenticate `middleware` in the priority list and that belongs to the `App` namespace. By targeting the marker interface in the Foundation HTTP Kernel and registering it here, the Foundation's middleware priority list and the application's can now match, making the application's unnecessary.

Utilize Authentication Middleware Contract 

---

config/database.php

This PR makes consistent types of configuration values in database configuration file. It's replacement of #5190
As @GrahamCampbell [said about database connections config](https://github.com/laravel/laravel/pull/5190#issuecomment-568814080):
> e.g. Consider the .env file:
> 
> ```
> DB_PORT=123
> ```
> 
> Then `env('DB_PORT', 3306)` will be the string "123", but if there is no variable, your code now produces an integer, which is not expected. We'd expect always a string, which is why the current implementation has the values quoted.
So I've tweaked redis config to match the same convention.

[6.x] Fix types consistency in Redis database config

---

app/Http/Kernel.php
app/Http/Middleware/HandleCors.php
composer.json
config/cors.php
routes/api.php

Based on a discussion with Taylor, I've added a HandleCors middleware similar to TrustProxies. This is using https://github.com/fruitcake/laravel-cors (formerly barryvdh/laravel-cors), which is updated with a few breaking changes to v1 (still in dev, awaiting possible feedback for this integration).
This would make it easy to implement CORS handling in Laravel, based on path matching.
An alternative approach would be route middleware, but the biggest issue is that it wouldn't match 404-routes, which would in turn lead to difficult debugging issues.
An approach could be to add a fallback route for the API middleware though, if you prefer route middleware, instead of the paths option.

[7.x] Add HandleCors middleware

---

package.json

Current laravel mix has a vulnerable dependency

[6.x] Update laravel mix and sass loader

---

package.json

This is not a fix for the vulnerability.
Just updating the dependencies to the latest version.

[6.x] Update cross-env and resolve-url-loader to the latest

---

config/view.php

this adds the option for https://github.com/laravel/framework/pull/31206
I am setting the default to check for expired files in non-production environments, and **not** check in production environments, to provide an example for what most people will probably use.  The only danger to this is you **must** run `php artisan view:cache` in deployment.
If you feel the risk it too great to automatically tie this to the environment, we can set the default value as `true`.

[7.x] add new `check_compiled` option

---

package.json

This is not a fix for the vulnerability.
Just updating the dependency to the latest version.
@see https://yarnpkg.com/package/cross-env
Yes, I know that they recently released version 6.0 and in a short time 7.0.

[6.x] Update cross-env to the latest

---

composer.json

Bumping `fzaninotto/faker` version to support PHP 7.4, especially when running composer with `--prefer-lowest` flag.
PRs related to version `^1.9.1`: 
* https://github.com/fzaninotto/Faker/pull/1748
* https://github.com/fzaninotto/Faker/pull/1843

[6.x] Bump fzaninotto/faker version to support PHP 7.4

---

phpunit.xml

PR https://github.com/laravel/laravel/pull/5139 added the xml schema to `phpunit.xml`. Because of this, IDEs like PhpStorm now show which attributes are redundant:
All the gray attributes in the screenshot above are setting the same value as the default value. They can be removed.
The `suffix="Test.php"` is also a redundant default, but I think this is useful in reminding people their test classes should end with `Test.php`

[6.x] Remove redundant default attributes from phpunit.xml

---

phpunit.xml

I'm not sure if there's a style rule for this, but it seems very out of place to be the only empty line in the whole file.

[7.x] remove empty line from phpunit.xml

---

config/queue.php

As described in laravel/framework#31784, this option will allow you to define a queue name suffix.
This can be useful in case you have multiple queues in multiple environments like in Laravel Vapor for example:
```yml
environments:
production:
queues:
- emails-production
- imports-production
staging:
queues:
- emails-staging
- imports-staging
```
So if you define your `SQS_SUFFIX` as either `production` or `staging`, your code can now look like this:
```php
dispatch(new SendWelcomeEmail($user))->onQueue('emails');
dispatch(new ImportEmailsCsv($path))->onQueue('imports');
```
or even like this:
```php
class SendWelcomeEmail implements ShouldQueue
{
/**
* The name of the queue the job should be sent to.
*
* @var string|null
*/
public $queue = 'emails';
}
```
```php
class ImportEmailsCsv …
```

[7.x] Add new SQS queue suffix option

---

app/Providers/RouteServiceProvider.php

This commit fixes the code indent of object operators, as following the framework code standards -> 2.4. Indenting

[7.x] Fix the code indent of object operators

---

config/cors.php

`exposed_headers` can be `false` or an array (not `true`). `max_age` can be false or an integer. 
There defaults make it more obvious.

[7.x] Update default CORS config

---

config/session.php

Hi,
Several changes reverted from #5157 (Symfony 5 update):
- Remove the null explicit default as env is null by default,
- Add null value in phpdoc as null is a totally valid value, (which is used by Symfony).
- Re-set null by default for same-site configuration, because as the phpdoc says itself "**By default, we do not enable this**", and I didn't find any clue of why this has be done, as it seems that nothing change for Laravel here in Symfony 5 update (new default for symfony Cookie, but Laravel set the value, so do not use the default see https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/HttpFoundation/Cookie.php#L91 and https://github.com/laravel/framework/blob/5c2c1df2d9d56f761e9c6352db067eb78426da62/src/Illuminate/Session/Middleware/StartSession.php#L157).
I'm …

Fix session config changes

---

config/mail.php

The default is the same as in `\Swift_Transport_EsmtpTransport::$params`
Complements https://github.com/laravel/framework/pull/31973

[7.x] Allow configuring the timeout for the smtp driver

---

config/filesystems.php

The reference to the changing the endpoint URL in s3 driver is named 'endpoint', not 'url'.
Also documented in the Flysystem docs:
https://flysystem.thephpleague.com/v1/docs/adapter/aws-s3-v2/#compatible-storage-protocols

[6.x] Fix S3 endpoint url reference

---

phpunit.xml

PHPUnit throw exception when Telescope is enabled

[7.x] Disable Telescope in PHPUnit

---

package.json

Disable host check when running laravel-mix hot.
Related issue: JeffreyWay/laravel-mix#1955

[6.x] Disable webpack-dev-server host check

---

app/Http/Middleware/TrustProxies.php

By default, this property is null. Therefore, it should be marked as nullable. Now the property declaration is the same as the parents, should we consider just removing it altogether in a future PR?
I ran into this when running some static analysis with https://github.com/psalm/psalm-plugin-laravel

[7.x] Update typehint to be nullable

---

README.md

British Software Development have rebranded to Many, link and link text updated accordingly.

Update sponsor link

---

composer.json

This pull request makes the Laravel skeleton require PHP 7.3. Note that, the [framework itself already requires PHP 7.3](https://github.com/laravel/framework/blob/9a7a475f895643e015dc287ddb7593cda2cff945/composer.json#L18).
Another note: Collision `^5.0` is not available yet, at the moment, this requirement will pull `v5.0.0-BETA3`.

[8.x] Requires PHP 7.3 and bumps both PHPUnit and Collision

---

app/Http/Middleware/RedirectIfAuthenticated.php

allow the middleware to have the same behavior as https://laravel.com/api/5.8/Illuminate/Auth/Middleware/Authenticate.html#method_authenticate
so now the guest middleware have the same footprint as auth ex.`guest:web,admin` instead of creating multiple lines for different guards.

[8.x] Multiple guards for RedirectIfAuthenticated

---

package.json

Bumps lodash from 4.17.13 to 4.17.19 to fix a security vulnerability. Most Laravel applications should not be affected but this PR will prevent the "security vulnerability" alert from GitHub on newly created Laravel applications. 
https://github.com/advisories/GHSA-p6mc-m468-83gw
Sourced from The GitHub Security Advisory Database:
> Prototype Pollution in lodash
> Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.
> 
> This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to …

Bump lodash from 4.17.13 to 4.17.19

---

phpunit.xml

After updating to Laravel 8 I suddenly had my test suite failing because telescope would not be disabled properly by `phpunit.xml` anymore.
This change fixed my test suite.
I've also created a clean Laravel 8 project and added some tests to demonstrate the issue:
https://github.com/hettiger/laravel-env-demo/commit/908d3405b84e769c12d296e98bef1ca567127254
Maybe this needs to be addressed in PHPUnit. However I'm adding this workaround here because it's a viable solution IMHO.
Maybe should add a note on this in the docs and be done with it…?

Fix PHPUnit bool server consts result in null

---

app/Providers/AuthServiceProvider.php

Due to the change of default model location in Laravel 8.x from /App to /App/Models, the initial policy comment shoud also reflect this change.

[8.x] Update model path in AuthServiceProvider's policies

---

app/Providers/RouteServiceProvider.php

Just uncommenting the namespace the routing doesn't work
https://medium.com/@litvinjuan/how-to-fix-target-class-does-not-exist-in-laravel-8-f9e28b79f8b4

[8.x] Fix route when uncomment $namespace

---

app/Providers/RouteServiceProvider.php

It was changed from per user to per application in ced3e50bca279f5a499a6d513fcdfd2a020c28ce
@iamgergo

Revert to per user API rate limit

---

package.json

Webpack v4 removed this flag so running `npm run dev` or `npm run prod` isn't working on this version. With the upcoming Laravel Mix v6 this would have come up as well probably. I'm already sending in this PR so Laravel 6 installs at least can make use of the new Webpack version. Will merge upstream.
See https://github.com/laravel/ui/issues/174

[6.x] Delete removed webpack flag

---

config/cache.php

In new versions of laravel we do not directly specify the "cache driver" anymore but rather a "cache store",
So it does not make sense to mention the list of drivers in the default section since laravel actually supports any arbitrary values as default cache store defined by the user.
I think it is misleading and the reader thinks that they are the only allowed values to be set as default.
Maybe you want to rename the env variable "CACHE_DRIVER" to "CACHE_STORE" for laravel 9.x (also in `.env.example`)

[8.x] Modify the cache.php docblocks

---

app/Http/Kernel.php

We recently learned of a vulnerability in our app through our Bug Bounty program which allowed an attacker to change the host of a signed URL using the `X-Forwarded-Host` header. This allowed an attacker to generate a malicious password-reset email which, if the link was clicked, would send the user's password reset token to a website controlled by the hacker.
Enabling this middleware by default could close this vulnerability for many websites who may currently be exposed to this same vulnerability.

[8.x] Uncomment TrustHosts middleware to enable it by default

---

.gitignore

Docker allows for you to override parts of `docker-compose.yml` locally with the help of a `docker-compose.override.yml` file: https://docs.docker.com/compose/extends/#understanding-multiple-compose-files
I propose to have this file ignored by default for new projects, similarly to how `.env` is ignored to be able to override default configuration (locally).
Example use case: Someone might want to use Laravel Sail, but would have multiple Laravel projects running in MySQL and would like to run a single MySQL server for each project and have a way to be able to override docker-compose to make that happen. Or maybe just in general they want to add a new service that they want to run only for themselves, and not for colleagues.

[8.x] Gitignore docker-compose.override.yml

---

composer.json

The Laravel Sail section (https://laravel.com/docs/8.x/sail) provides a list of arguments that we can use with the 'sail' command. Some of the arguments are 'not found' after the fresh install(e.g. https://laravel.com/docs/8.x/sail#sharing-your-site).
The laravel/sail package is updated to the v1.0.1.

Update sail to the v1.0.1

---

package.json

This PR upgrades Laravel Mix to v6. 
The update to `package.json` should be all that we need here, but we should also take a look at some of the presets. 
- **Upgrade Guide**: https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md
- **Changelog**: https://github.com/JeffreyWay/laravel-mix/blob/master/CHANGELOG.md
I've also made a PR to the docs.
https://github.com/laravel/docs/pull/6705

Upgrade to Mix v6

---

package.json

Security Vulnerability: https://www.npmjs.com/advisories/1594
Super minor issue but saves those installing Laravel from having to manually resolve this.

Update to package.json - Axios Version

---

.gitignore

Using the Laravel curl installation command, it creates a `.env.bak` file instead of `.env.backup`. Changing the .gitignore to `.env.ba*` hides both.

[8.x] Hide .env.bak as well as .env.backup in .gitignore

---

docker-compose.yml

To avoid port clash between different projects running on the same machine, it could be useful making mailhog's port configurable.

[9.x] Mailhog's forward ports configurable

---

composer.json

This pull request bumps the Collision version, to a version that supports Parallel Testing: https://github.com/laravel/framework/pull/35778.

[9.x] Bumps Collision version

---

config/broadcasting.php

'ably' was added in the connections array, but the comment was not updated to reflect this fact.

add "ably" in comment as a broadcast connection

---

database/factories/UserFactory.php

This will add an unverified state to the User model factory to give an example for newcomers of how to use states in the new 8.x syntax. It also serves as a useful addition when writing feature tests where the faked user is intended to not have their email verified yet.

[8.x] Add unverified state to UserFactory

---

resources/views/welcome.blade.php

As this is used as a verb, like its sibling "Register", the verb form ("Log in") should be used, instead of the noun form ("Login").
The full argument is here: http://notaverb.com/login and https://grammarist.com/spelling/log-in-login/
The short version is: the past tense is "logged in" not "logined", so the present imperative tense is "log in" (but you can use "login" as a noun, as in "I have a login on that site").
This also would bring Laravel in line with things like Facebook, Twitter, WordPress, Drupal, and more.
If accepted, I'm happy to open PRs for Jetstream and Breeze, which in addition to using "Login" as a verb in several places, also use "Logout", about which the same arguments apply.

Change "Login" text to "Log in"

---

app/Exceptions/Handler.php

With starter packs like Jetstream, the `current_password` input is used.
I believe that adding `current_password` to the `$dontFlash` list by default would help to ensure new projects follow security best practices from the get-go.

Don't flash 'current_password' input

---

composer.json

fixes CVE-2021-3129 vulnerability (Laravel 6)

[6.x] target 1.16.15 of facade/ignition for Laravel 6.x

---

app/Http/Middleware/TrimStrings.php

Inspired by https://github.com/laravel/framework/pull/36415
As JetStream/Fortify uses a `current_password` field when allowing a user to change their password, and as JetStream is one of the starter kits listed on the docs, this PR adds `current_password` in the `$except` option of the `TrimStrings` middleware.

[8.x] Don't trim `current_password`

---

config/queue.php

There's a new `after_commit` config option that isn't in the default config for `queue` connections: 
https://laravel.com/docs/8.x/queues#jobs-and-database-transactions
For new projects it may be better to have these defaulted to `true`, but I left them as `false` for now.

[8.x] Add missing 'after_commit' key to queue config

---

resources/lang/en/validation.php

Just adding in language for the new `prohibited_if` and `prohibited_unless` validation rules introduced in 8.x (https://github.com/laravel/framework/pull/36516)
I've mirrored the wording of the "required" validation rules as they *currently* stand, but may need to tweak this depending on the result of #5553.

[8.x] Add language for prohibited_if and prohibited_unless validation rules

---

config/app.php

All other facades have an alias (except for ParallelTesting - which I don't think needs one). 
I think having an alias for this makes sense as it can by handy in views to be able to work with dates that aren't always coming from a model where a cast is usable and an alias makes this nicer as we don't need to import the namespace. It is also handy in tinker to just call `Date::parse()` to test some stuff on the fly.
Related: https://github.com/laravel/docs/pull/6897

[8.x] Add date facade alias

---

config/logging.php

All other channels nicely respect the `LOG_LEVEL` env variable, but it is missing for the `stderr` channel by default.

Add log level config value to stderr channel

---

resources/views/welcome.blade.php

Before:
After:
I wanted to display the nav links on mobile as well but that turned out to be a little too challenging.

[8.x] Fix footer on mobile

---

config/filesystems.php

There is a difference between `disk` and `driver` and the `default` key in `filesystems.php` is the default for disks, not drivers.
And developers may be confused when they see the filesystem config file.
I guess you should fix this in the new version.

[9.x] Change default disk env key

---

tests/Feature/ExampleTest.php
tests/Unit/ExampleTest.php

We decided a while back to go for snake case as our convention for methods names in tests. All of our other first party libraries except for the framework are already on this convention. This PR moves the skeleton to the same convention. We'll convert the framework as well at some point.
Note that these new method names reflect the ones from the stub files in the framework when scaffolding a test using `make:test`. This also removes the duplicate "test" word.

[8.x] Rename test methods

---

database/factories/UserFactory.php

After Faker PHP 1.14, using properties is deprecated, and it is recommended to use methods instead.
See [#164](https://github.com/FakerPHP/Faker/pull/164) for details.
It shouldn't be a breaking change.

[8.x] Using faker method instead of properties

---

composer.json

Security advisory: [GHSA-4mg9-vhxq-vm7j](https://github.com/laravel/framework/security/advisories/GHSA-4mg9-vhxq-vm7j)

[8.x] Bump framework version to include SQL server security fix

---

config/cache.php

This PR adds Octane cache store to `cache.php` config in order to fix `Cache store [octane] is not defined.` error when using the Octane powered cache and ticks.

Add Octane cache store

---

.gitignore

Add folders to gitignore. The same exclusions exist in the laravel / framework gitignore.

Add folders to gitignore

---

resources/lang/en/validation.php

This PR adds the required translation line for the current_password rule introduced in [#37650](https://github.com/laravel/framework/pull/37650).

[8.x] Add translation for current_password rule

---

resources/lang/en/validation.php

"zone" is ambiguous
Reference:
https://laravel.com/docs/8.x/validation#rule-timezone
```diff
-    'timezone' => 'The :attribute must be a valid zone.',
+    'timezone' => 'The :attribute must be a valid timezone.'
```

[8.x] Update validation.php timezone

---

resources/lang/en/validation.php

Reference to docs:
https://laravel.com/docs/8.x/validation#rule-url
#url
The field under validation must be a valid URL.
```diff
-    'url' => 'The :attribute format is invalid.',
+    'url' => 'The :attribute must be a valid URL.',
```

[8.x] Update validation.php for URL

---

config/app.php

#5556 added the `Date` facade alias and claimed that only `ParallelTesting` didn't have (and doesn't need) an alias. However, `RateLimiter` does not have an alias either. This MR fixes that.
By the way, the missing `RateLimiter` alias seems to have caused [an issue when using Psalm](https://github.com/psalm/psalm-plugin-laravel/issues/134), but of course the main reason to add that alias is consistency.
PS: Maybe it would even make sense to add a `ParallelTesting` alias, but to comment it out like the `Redis` alias. 🤔

[8.x] add RateLimiter facade alias

---

app/Http/Kernel.php
composer.json

I had to remove collision and Laravel CORS to make this work. As soon as those two libraries are patched for Symfony v6 we can re-add them.﻿

[9.x] Allow develop installs

---

app/Http/Middleware/TrustProxies.php
composer.json

This uses the new TrustProxies middleware from https://github.com/laravel/framework/pull/38295. This way we can safely drop the dependency on fideloper/proxy.﻿
I wasn't 100% sure to directly use the middleware in the Kernel instead of overwriting it like now. The current property values are exactly the same as the parent class. But you could argue that this is an easier starting point for people wanting to overwrite them.

[8.x]  Use new TrustProxies middleware

---

app/Http/Kernel.php
app/Models/User.php
composer.json
config/auth.php
config/sanctum.php
database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
routes/api.php

This PR serves as a proof of concept for what it would look like to just make Sanctum the default API authentication stack in a new Laravel application.
**Motivations:** The `token` driver is not robust and is no longer documented as of the Laravel 8.x release many months ago. As in, there is literally no documentation on the website about how to use it because I simply don't think it is a good idea to ever use it.

[8.x] Sanctum

---

app/Providers/RouteServiceProvider.php

This PR leverages php 8 "null safe operator" instead of thrr `optional()` helper

[9.x] Use php 8 null safe operator

---

config/mail.php

laravel/framework#38344 introduced a failover driver for mail. `config/logging.php` includes the scaffold for a "stack" driver, so it makes sense that `config/mail.php` should also include the scaffold for a "failover" driver as they're in the same vein.

Add failover driver to default mail config file

---

app/Http/Middleware/TrustProxies.php

When installing a new project with `laravel new` and installing `squizlabs/php_codesniffer`, the projects has one error that cannot be fixed automatically by `phpcbf` because the `app/Http/Middleware/TrustProxies.php` class has a line of more than 120 characters.
Laravel is supposed to follow the PSR-2 conventions : https://laravel.com/docs/8.x/contributions#coding-style
To reproduce :
```bash
laravel new test-coding-standards
cd test-coding-standards
composer require squizlabs/php_codesniffer
vi phpcs.xml
```
Small phpcs.xml file :
```xml
<?xml version="1.0"?>
<ruleset name="PHP_CodeSniffer">
<description>The coding standard for our project.</description>
<rule ref="PSR2"/>
<file>app</file>
<file>bootstrap</file>
<file>config</file>
<file>database</file>
<file>resources</file> …
```

Fixing "Line exceeds 120 characters" in TrustProxies to comply with PSR-2

---

app/Models/User.php

Use PHPDoc comments from base class to stay consequent.

[8.x] Use PHPDoc comments from base class in User model

---

config/mail.php

Symfony Mailer doesn't support auth_mode anymore because the server will negotiate the auth_mode for you.
PR: Where it was removed: https://github.com/laravel/framework/pull/38481
Why Symfony doesn't support it anymore full answer: https://github.com/symfony/symfony/pull/33237

[9.x] Remove auth_mode from config/mail.php

---

config/mail.php

I can see a new mail driver failover has been added. I would like to add this driver in comment section as a supported driver.

[8.x] Add failover in supported mail configurations comment section

---

composer.json

This pull request ensures the download version of Collision in new Laravel projects support PHP 8.1.

[8.x] Ensures downloaded version of Collision supports PHP 8.1

---

composer.json
tests/Feature/ExampleTest.php
tests/TestCase.php

This pull request makes `LazilyRefreshDatabase` a default trait on the base test class for every new Laravel project. This way people don't need to worry about which test cases use the database or not - things will just work.
If this pull request gets merged, we may need to adapt the documentation before next week's release.

[8.x] Uses `LazilyRefreshDatabase` by default

---

resources/lang/en/validation.php

The grammar for gte.numeric/file/string and lte.numeric/file/string do not currently appear to follow the concept of parallel structure, so can sound a little strange to some people's ears. To be parallel, we need the preposition for "equal" (to match the adjective + pronoun used with "greater than"), which would be "to" in this case. Given that these are short messages that are potentially seen by many people, I think having the grammar corrected would be good for the professionalism of those using Laravel as a framework.
Thanks!

Update lte and gte validation messages to have a grammatically parallel structure

---

public/index.php

`Kernel@handle` contract returns `\Symfony\Component\HttpFoundation\Response`, which in turn has a method `send()` that returns itself (`Response`). So there is no need for wrapping Response in HigherOrderTapProxy each time.

[8.x] Remove redundant tap() helper in index.php

---

resources/lang/en/validation.php

Adds declined and declined_if validation rules to the translation files.
Should only be merged if feature PR (https://github.com/laravel/framework/pull/39579) is merged.
Documentation PR: https://github.com/laravel/docs/pull/7425
Framework PR: https://github.com/laravel/framework/pull/39579

[8.x] Added declined and declined_if validation rules

---

config/database.php

Per https://github.com/laravel/framework/pull/35588 , the term "schema" (a namespace) has been corrected to "search_path" (a list of namespaces), where appropriate, throughout the framework.
Accordingly, the `schema` configuration key should be changed to `search_path` to better reflect the fact that it may specify a _list_ of schemata (schemas), and not just a single schema. (In several Laravel versions prior to 9.0, the `schema` key could already specify more than one schema, but this fact was undocumented and non-obvious without examining the implementation carefully.)
As of Laravel 9.0, the `search_path` may specify any number of schemata, in any of the following formats:
'search_path' => 'public',
'search_path' => 'public,laravel',
'search_path' => ['public', '"laravel"', "'foobar'", …

Replace schema with search_path in pgsql config

---

app/Console/Kernel.php

This pull request proposes the removal of the `Console\Kernel::$commands` property by default.
It's been a while since Laravel has introduced the possibility of loading commands from a specific folder, and since then, I don't remember the last time I've used this property.
Of course, just like multiple properties today on modals, for example, people can add back this property when they want.

[8.x] Removes the `Console\Kernel::$commands` property

---

composer.json

Thank you @sebdesign for the fix. See https://github.com/laravel/laravel/pull/5654#issuecomment-977988782. The `vendor:publish` command will not update files if they already exist, without the `--force` parameter. Horizon and Telescope's publish commands add the force param, so we need to add it here also.

[8.x] Fix asset publishing if they were already published

---

app/Exceptions/Handler.php
app/Http/Kernel.php
app/Http/Middleware/EncryptCookies.php
app/Http/Middleware/PreventRequestsDuringMaintenance.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Http/Middleware/TrimStrings.php
app/Http/Middleware/TrustHosts.php
app/Http/Middleware/TrustProxies.php
app/Http/Middleware/VerifyCsrfToken.php
app/Models/User.php
app/Providers/AuthServiceProvider.php
app/Providers/EventServiceProvider.php

This pull request is a follow up for https://github.com/laravel/framework/pull/38538, and it improves the DX of Laravel's skeleton on editors like PHPStorm that now support generics. And of course, it also improves the DX with static analyse tools in the process.
Here is a few examples where the DX was improved while using PHPStorm:

[8.x] Improves generic types on the skeleton

---

config/mail.php

Testing this in an application, it would seem that sendmail -bs is the wrong option for this case?
What Laravel appears to do is pipe an RFC-2822 formatted message on STDIN and requires the sendmail emulation to deal with it,
rather than -bs which initiates an SMTP session.
if Exim is the default MTA then -t would seem to be the correct option.
If you have an alternative installed instead of sendmail/exim, then there's no way to set the path, so I added MAIL_SENDMAIL_PATH
so you can do, e.g.:
MAIL_SENDMAIL_PATH="/usr/bin/msmtp -t --tls=off --from=${MAIL_FROM_ADDRESS} --auto-from=off"
msmtp doesn't support -bs at all

[8.x] Add option to set sendmail path. Fix default

---

config/broadcasting.php

Framework PR: https://github.com/laravel/framework/pull/39924
This PR just adds the information that `client_options` can be passed.

[9.x] Add client_options to Pusher driver

---

composer.json

So minimum installs for new apps is similar to the latest security advisory patch.

Bump Laravel to v8.75

---

public/index.php

Simplify the calling of maintenance file by assigning it to variable so you don't have to write it twice

Simplify the maintenance file call

---

phpunit.xml

This changes the default configuration to avoiding a developer experience where you spend hours trying to determine why your CI configuration is not working.
The `<server>` element has a higher than system environment variables (e.g. `export APP_ENV=ci`). As such, anything currently set in `phpunit.xml` can only be overridden by setting the configuration within your application (e.g. `app()->config('app.env', 'ci')`).
The `<env>` element is lower than system environment variables. For more detail, I wrote about [configuration precedence during testing](https://jasonmccreary.me/articles/laravel-testing-configuration-precedence/).
Considering this repo is static, this could likely be retargeted at `8.x`. However, I felt the upcoming `9.x` release provided a clean transition point.

[9.x] Use <env> element

---

config/app.php

Following https://github.com/laravel/framework/pull/40453, this pull request adjusts the skeleton `Facade::defaultAliases()` usage.

[9.x] Improves app's default aliases configuration file

---

phpunit.xml

This pull request makes the routes file to be analysed in terms of test coverage. This is necessary, as just like `./app`, the files within the routes folder contain application code.

[9.x] Analysis routes files test coverage

---

composer.json

This pull request bumps `nunomaduro/collision` dependency to ensure people get the `--coverage` option even when running a `composer update  --prefer-lowest`.

[9.x] Bumps `nunomaduro/collision` dependency

---

config/session.php

In previous releases of Laravel, the PHP `serialize` and `unserialize` functions were used to serialize the session data for storage. In general, this is fine since all Laravel session cookies are encrypted and signed using message authentication; therefore, they can't be tampered with by the client and raw user, controlled input can not make it into the `unserialize` function.
However, if the application encryption key (`APP_KEY`) is compromised, user controlled input could be passed to the `unserialize` function by crafting an encrypted cookie using the stolen encryption key. This could lead to remote code execution.
This changes the default behavior of new Laravel 9 applications to use JSON encoding to serialize session data. Applications upgrading from Laravel 8 may continue using PHP …

[9.x] Change session serialization defaults

---

config/hashing.php

I noticed 2 problems with the default Argon2 options.
When first introduced, the indicated values for memory cost, time cost and threads for Argon2 hashing was the same as defined in their PHP constant counterparts. However, they have since been updated in [PHP bug #78269](https://bugs.php.net/bug.php?id=78269), where the old defaults are called "weak".
New values are as follows:
```
'argon' => [
'memory' => 65536,
'threads' => 1,
'time' => 4,
],
```
A second issue arises when using the old values on PHP supplied from Remi's RPM repository, e.g. on RHEL. For creating new hashes, [PHP here relies on libsodium (on PHP version 7.4 onwards)](https://forum.remirepo.net/viewtopic.php?id=3961), which [does not support a thread value > 1](https://wiki.php.net/rfc/sodium.argon.hash#additional_chang …

Update the default Argon2 options

---

.styleci.yml

As `server.php` was removed in #5747, this is no longer needed in the StyleCI configuration file.

[9.x] Remove `server.php` from StyleCI

---

phpunit.xml

This pull request reverts analysing routes folder coverage as it seems to cause issues with different coverage reporters than the one we added for L9.

[9.x] Reverts analysing routes folder coverage

---

.gitattributes

`lf` EOL is defined in `.editorconfig` but missed in `.gitattributes`, so here is the fix.
This little fix helps keep the EOL consistent across the project and ensures it doesn't get messed up by GitHub Desktop or any other GIT client.

Fix .gitattributes consistency with .editorconfig

---

database/factories/UserFactory.php

This fixes some PHPStan issues in the user factory (I tested at level 8)
```
------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Line   database/factories/UserFactory.php                                                                                                                                    
------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
18     Method Database\Factories\UserFactory::definition() return type has no value type specified in iterable type array.                                                   
💡 See: …
```

[9.x] Improve typing on user factory

---

.gitattributes

Reverts laravel/laravel#5802
I don't feel this is needed since this would apply only in userland, not when developing this skeleton repo. The editorconfig file already has the proper eol defined for the project.

[8.x] Revert "Fix .gitattributes consistency with .editorconfig"

---

config/app.php

Following up with #5791.
After a quick search using the following Regex `env\(['"]{1}(.+)['"]{1},\s*null\)`, this is the last one in `laravel/laravel`.

[9.x] Remove redundant `null`s

---

config/app.php

This adds the comment for the `Redis` facade which was present in < 9.x and was there for easy activation.
https://github.com/laravel/laravel/blob/6c1f430aa76809084668f9a97121bd2ca8bafa10/config/app.php#L221

[9.x] Add Redis facade as comment in app.php config file

---

config/cache.php

For Redis caching prefix with underscore : 
'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
but when cache stored in database, then the key is created "merged" with prefix, by this line:  'prefix' => env('CACHE_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_cache'), for example, if "key" is a key for cache, then the result is: "laravel_cachekey", not a preferable "laravel_cache_key"

Add underscore to prefix in database cache key

---

app/Providers/RouteServiceProvider.php

Since we removed the namespace property in https://github.com/laravel/laravel/pull/5816 we can also remove the namespace method from the routes which uses this property

[9.x] Remove namespace from Routes

---

app/Http/Kernel.php
composer.json

Depends on https://github.com/laravel/framework/pull/41137 which also needs to be tagged first.

[9.x] Replace Laravel CORS package

---

config/services.php

Adds a config option to allow overriding the Mailgun transporter scheme. See also https://github.com/laravel/framework/pull/41309.

[9.x] Add option to configure Mailgun transporter scheme

---

config/filesystems.php

Ref PR https://github.com/laravel/framework/pull/41308
I kept it `false` so it does not change the current behaviour.
One can make it `true` to get errors related to file operations such as uploading to S3 via `Storage::put()`
Thanks.

[9.x] add `throw` to filesystems config

---

config/mail.php

This is needed to solve an issue with BCC recipients in the new Symfony mailer. This has come up on Symfony's issue tracker: https://github.com/symfony/symfony/issues/40070 and was discussed in a PR: https://github.com/symfony/symfony/pull/39744. Basically it comes down to `-bs` being preferred over `-t`. I don't know exactly the deep explanation for this but it seems to help the OP from the below issue. `-bs` is also the default in the Sendmail Mailer from Symfony. 
See https://github.com/laravel/framework/issues/41357.

[9.x] Update sendmail default params

---

config/app.php

Now that we no longer have all the defaults (#5769), it would be helpful if we had one example of how to write one.

[9.x] Add an example to the class aliases

---

lang/en/validation.php

The `password` rule was replaced by `current_password` so it seems like the former can be removed now, which would be in line with what was said [here](https://github.com/laravel/laravel/pull/5628#issuecomment-859629877)

[9.x] Remove "password" from validation lang

---

composer.json

Required for password rule translations to work properly (see https://github.com/laravel/framework/pull/42060)
In the current skeleton, if someone was to update the `password` entries in `validations.php` and resolved an older `laravel/framework` version, the changes would not affect the actual displayed message, which could be quite confusing.

Bump laravel/framework version to latest

---

lang/en/validation.php

Sorting the newly added `password` rules in alphabetical order.

[9.x] Fix alphabetical order for password rules

---

config/mail.php

Add `local_domain` as an option to the smtp configuration. This can be used to change the domain that is used to send the `EHLO` command during the SMTP handshake.
`null` is a sensible default since Symfony/Mailer will use it's own default (`127.0.0.1`) to send the mail.
I stumbled upon this option while trying to figure out why the [Google Relay Service](https://support.google.com/a/answer/2956491) stopped working. 
From their docs:
> We recommend that you configure your mail server to present a unique identifier (such as your domain name or the name of your mail server) in the HELO or EHLO command in the SMTP relay connections your server makes to Google. Avoid using generic names such as "localhost" or "smtp-relay.gmail.com," which can occasionally result in issues with DoS limits.
By …

Add local_domain option to smtp configuration

---

resources/js/app.js
resources/js/bootstrap.js

The Laravel skeleton currently uses Node/CommonJS `require()` statements to load several dependencies. These statements are not supported when using Vite because it exclusively leverages ES Modules (which use the `import` syntax) to achieve lightning-fast speeds.
This PR replaces the `require` statements with equivalent `import` statements to make the transition to Vite smoother. Webpack supports both, so this should have no noticeable impact for Mix users other than improving type information in their IDEs :nerd_face:

[9.x] Switch to ESM imports

---

.gitignore

An `auth.json` is commonly used when working with Nova, etc. I feel like this should be a default in the Laravel skeleton since the ecosystem uses it quite a bit. This will help developers from accidentally committing sensitive credentials.

[9.x] Add auth.json to skeleton

---

.github/workflows/tests.yml

This PR bumps `actions/checkout` dependency to the latest version. No breaking changes.

[9.x] Bump `actions/checkout` dependency

---

vite.config.js

This PR makes the skelton come with the default Laravel watching configuration out of the box.
As it stands, this will perform a full page refresh while running `npm run dev` and saving files within the following directories:
```
resources/views/**
routes/**
```
The directories can still be manually configured when needed.
See: https://github.com/laravel/vite-plugin/pull/43

[9.x] Add default reloading to skeleton

---

package.json

The `laravel-vite-plugin` had a pre-1.x major version bump due to a change in the plugin return type.

Update to the latest version of laravel-vite-plugin

---

package.json

- https://github.com/laravel/vite-plugin/pull/77
> **Warning**: ~~We need to specify the version constraint. I've left it as `TODO` as I was not sure if we would be tagging versions between commit and when we merge this.~~ Jess: Done!

[9.x] Vite 3 support

---

.styleci.yml
vite.config.js

Whether the list is multi-line is controlled by single-line length. Once it exceeds the threshold, it is moved to multi-line.

[9.x] Don't need to ignore vite config file

---

app/Http/Kernel.php
app/Http/Middleware/ValidateSignature.php

This provides a work around to an interesting problem with Signed URLs that I encountered and discussed here: https://twitter.com/valorin/status/1547053470389112834.
I've created a PR for the framework here: https://github.com/laravel/framework/pull/43160
The problem is that some systems, such as mailing list providers and Facebook will add their own tracking parameters onto URLs. Such as the [UTM tracking parameters](https://usefathom.com/utm-builder) (`utm_*`), and Facebook's `fbclid` parameter,  which it adds to any links clicked for tracking purposes.
Since these are added as query parameters, they break the signature and prevent the URL from being validated.
My solution is to replicate the design used in other core middleware (i.e. `EncryptCookies`, …

Add ValidateSignature middleware for ignore params

---

database/factories/UserFactory.php

When seeding large amounts of users there is a chance for a duplicate entry SQL error because the [email column is unique](https://github.com/laravel/laravel/blob/64e01753985749fab6626a370b27baa8431e74e6/database/migrations/2014_10_12_000000_create_users_table.php#L19).

Make email unique

---

.github/workflows/tests.yml
.github/workflows/update-changelog.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

.gitignore

According to v9.32.0 release, has been introduced  env:encrypt and env:decrypt commands
To encrypt production env you need to create `.env.production` file first then you can encrypt it become `.env.production.encrypted`
The problem is `.env.production` is not ignored by default, this really dangerous if it's accidentally committed and pushed to repository, your credential will be exposed!

ignore .env.production

---

.gitignore

Since [JetBrains Fleet](https://www.jetbrains.com/fleet/) has been released, we should add its config folder to `.gitignore` for consistency, like it is done with `.idea` and `.vscode` directories.

Add /.fleet directory to .gitignore

---

README.md

The old badge was still referencing Travis CI, last time that ran was 2 years ago.

Updated tests badge

---

resources/views/welcome.blade.php

This updates the icons on the welcome page to the new Heroicons v2 ones. I also changed the Laracasts icon to a 
video camera one which seemed more applicable than a photograph camera.
Before:
After:

Update to Heroicons v2

---

resources/js/bootstrap.js

As of [pusher-js v8.0 release](https://github.com/pusher/pusher-js/releases/tag/v8.0.0) a cluster option is now required.
Without this option pusher-js v8.0 is throwing an error.

[9.x] Support pusher-js v8.0

---

database/migrations/2014_10_12_100000_create_password_resets_table.php

Switching from a normal index here to a primary index behaves the same except for adding a `UNIQUE` constraint.
The `DatabaseTokenRepository` deletes existing records with an email first, before creating a new one, so this additional constraint will be okay. https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php#L88
Something similar was tried in #5652, but that PR added an **additional** `id` field as the primary key, which is probably a little overkill since we can just use the existing `email` field.
I have confirmed this solves the problem when the database has `SQL_REQUIRE_PRIMARY_KEY` set to `TRUE`, as it is on DigitalOcean Managed Databases.  I would say this is a good change to the default Laravel skeleton, as it is recommended to …

[9.x] switch password reset email to a primary key

---

app/Console/Kernel.php
app/Exceptions/Handler.php
app/Http/Middleware/Authenticate.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Http/Middleware/TrustHosts.php
app/Providers/AppServiceProvider.php
app/Providers/AuthServiceProvider.php
app/Providers/BroadcastServiceProvider.php
app/Providers/EventServiceProvider.php
app/Providers/RouteServiceProvider.php
database/factories/UserFactory.php
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2014_10_12_100000_create_password_resets_table.php
database/migrations/2019_08_19_000000_create_failed_jobs_table.php
database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
database/seeders/DatabaseSeeder.php
tests/CreatesApplication.php
tests/Feature/ExampleTest.php
tests/Unit/ExampleTest.php

This section, contains the list of next steps, and details the release this feature:
1. @taylorotwell should validate the code on the following pull requests, so @driesvints can merge those pull requests on `master`:
2. @taylorotwell should validate the code **and merge** on the following pull requests, so @driesvints can release:
> @taylorotwell @driesvints Once `laravel/fortify` is released, bump `laravel/fortify` version, and release:
> @driesvints Once `laravel/cashier-paddle` and `laravel/cashier-stripe` is release, bump their versions on `spark-paddle@v3` and `spark-stripe@v3`, and release:
3. Near the Laravel `v10.x` release date, perform the following tasks:
4. Coordinate with the Nova team, and ensure this pull requests are already included on the `5.x` branch:
---
This pull …

[10.x] Uses PHP Native Type Declarations 🐘

---

app/Http/Middleware/Authenticate.php

Before the official Laravel 10 release I want to [revisit this conversation](https://github.com/laravel/laravel/pull/6010/files#r992625264). This is the only instance of a union type being used over a nullable type in the new skeleton code. As such it sets a _precedent_ since many developers look to the documentation or source code for conventions.
If Laravel prefers to use explicit union types over nullable types, please close my PR. If the streamlined nullable type is preferred, then 🏄‍♂️ 
Please note, it is not my intention to start the Type Wars of 2023. I mostly want to finish the conversation so I may code the _Laravel 10.x Shift_ accordingly.

Use nullable typing

---

config/app.php

If there is no `ASSET_URL` for a Laravel project, Laravel will fallback to appending the current request's host. It ignores the `APP_URL`.
```php
APP_URL=https://app-url.com
ASSET_URL=
```
If the site is served at `http://127.0.0.1:8008`...
```php
asset('style.css');
// http://127.0.0.1:8000/style.css 
```
This works great for the backend, but Vite will never know what the host of the request is, as all its knowledge must be known at build time. So Vite and Laravel can not truly share the asset URL across the build time / runtime divide _when `ASSET_URL` is empty_.
**Why is this a problem?**
Laravel outputs preload tags for all the required assets for the initial page load (hashes removed for readability).
```html
<link rel="modulepreload" …
```

[10.x] sets ASSET_URL to use `/` as the fallback value

---

.gitignore
composer.json
phpunit.xml

This pull request adds PHPUnit 10 support to Laravel. Note that, before any release here on the skeleton, the following tasks need to be performed first:
1. [x] Merge and release: https://github.com/laravel/framework/pull/45416.
2. [x] Ensure Collision `^7.0` is released with support for Parallel Testing ( it may take a while ).
3. [x] Adjust the `composer.json` with the latest version of `laravel/framework`, and release this pull request.

[10.x] Adds PHPUnit 10 support

---

config/auth.php

Currently the throttle setting in `config/auth.php` is not documented, I added a small description so that user can easily undersand the setting

[9.x] Adds clarification to throttle auth setting

---

resources/views/welcome.blade.php

This pull request tweaks the "Documentation" section of our welcome screen to avoid an extra line when displaying the welcome screen.
Here is before:
Here is after:

[10.x] Small tweak in `welcome` screen

---

composer.json

[php-http/discovery](https://packagist.org/packages/php-http/discovery) is widely used by SDK authors to provide auto-discovery of PSR-17/18 implementations. It's widely used in all PHP communities (Laravel, Symfony, etc.)
Since v1.15, it became a composer plugin, see https://github.com/php-http/discovery/pull/208. Adding this line improves DX by removing one needless prompt by Composer when the package is (transitively) required when installing a dependency. This takes a similar approach to #5959.
You might want to check the README of https://github.com/FriendsOfPHP/well-known-implementations for back ground on why this became a plugin.
For cross-ref, Symfony's skeleton also enabled this by default, see https://github.com/symfony/skeleton/pull/214

Allow php-http/discovery as a composer plugin

---

database/factories/UserFactory.php

Remove redundant `@return` docblock in `UserFactory`.
```php
public function unverified(): static
{
...
}
```
already shows what it returns

Remove redundant `@return` docblock in UserFactory

---

config/app.php

See the comments in #6089
tl;dr; The asset helper does not generate usable URLs on the console and for emails out of the box. I would rather have good URLs in emails out of the box than to remove some duplicate noop tags output from Vite.

Reverts change in asset helper

---

config/logging.php

This is not mentioned in the documentation so there was no way to know how to specify a facility like `local0` unless you go digging in `\Illuminate\Log\Logmanager`'s source code, which IMHO should not be necessary to figure out what options are available.
Another solution would be to add it to the documentation, but I believe it's simpler to just have it in the default config file.

[10.x] Specify facility in the syslog driver config

---

config/logging.php

Following https://github.com/laravel/framework/pull/46344.
Add `replace_placeholders` to `true` to log channels and `PsrLogMessageProcessor` for `monolog` driver channels.
By default with this configuration, new applications will be able to do:
```php
Log::info('Showing the user profile for user: {id}', ['id' => $id]);
```

[10.x] Add replace_placeholders to log channels

---

config/queue.php

Hey there 👋 
This PR adds the job batching configuration options to the queue configuration skeleton, so it's easier to tell that it's possible to customize which database connection and table name is used.
I have several applications which are all using the same database, and today I was changing which table they were using for their failed jobs, as they were all using the default  `failed_jobs` table.
I thought that job batching was going to be a problem, but I found that it was already possible to customize by looking inside the BusServiceProvider [here](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Bus/BusServiceProvider.php#L49).
I should also mention that I did not find anything in the [docs](https://laravel.com/docs/10.x/queues#job-batching) describing this. …

Add job batching options to Queue configuration file

---

composer.json
phpunit.xml

This pull request adds `phpunit/phpunit@10.1` support, and it should be merged, and released, once PHPUnit 10.1 is out. 
At this moment, because the `phpunit.xml` contains deprecated options, users will see:
```
Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
```

[10.x] Adds `phpunit/phpunit@10.1` support

---

composer.json

It seems like the constraints where not updated.
But the class `DefaultProviders` only exists since 10.8

Fix laravel/framework constraints for Default Service Providers

---

package.json

Full description: https://github.com/laravel/vite-plugin/pull/189
See:
- https://github.com/laravel/vite-plugin/pull/189
- https://github.com/laravel/breeze/pull/246
- https://github.com/laravel/jetstream/pull/1242

[10.x] sets package.json type to module

---

app/Models/User.php
composer.json

This PR adds the new `hashed` cast to the user password field.
I left the user factory with the already hashed password since this cast first checks if the field needs rehash (this check doesn't affect the performance).

Add hashed cast to user password

---

config/broadcasting.php

We use Laravel Echo and Pusher in our first party Statamic Collaboration Addon https://github.com/statamic/collaboration, and notice that users are having problems connecting via Laravel Echo websocket in newer Laravel versions where `cluster` no longer exists in the default Pusher config.
We notice it was [added to the example in bootstrap.js](https://github.com/laravel/laravel/pull/6059) because pusher-js 8.0 now requires `cluster`. With this requirement, and with our Collaboration Addon reading from the users' Laravel config, we're thinking that it should be accessible through the default Laravel config as well, and so that the config can be cached, etc.
Your thoughts?

[10.x] Bring back pusher cluster config option

---

app/Http/Kernel.php

This PR adds a `precognitive` to the middleware aliases array so we can use `precognitive` in the route instead of the fully qualified class name.

Add `precognitive` key to $middlewareAliases

---

config/mail.php

This PR defines `ses-v2` as default `ses` mail transport.

[11.x]: Use `ses-v2` as default `ses` mail transport

---

package.json

Bumps `laravel-vite-plugin` to `v0.8.0`

Bump `laravel-vite-plugin` to latest version

---

config/mail.php

as mentioned in the following
ref https://github.com/craigpaul/laravel-postmark/issues/141
Postmark allows the mailer configuration to accept the `stream_id`, this is helpful if you sent transaction and broadcast notifications from Laravel with Postmark.

Postmark mailer configuraiton update.

---

config/database.php

The project skeleton still uses the old `utf8mb4_unicode_ci` MySQL v5.x collation. This causes problems with things like emojis when using MySQL 8. `utf8mb4_0900_ai_ci` is the correct collation for MySQL v8.
From the [MySQL v8 reference manual](https://dev.mysql.com/doc/refman/8.0/en/charset.html):
> The default MySQL server character set and collation are `utf8mb4` and `utf8mb4_0900_ai_ci`, but you can specify character sets at the server, database, table, column, and string literal levels.
Example of a problem when using `utf8mb4_unicode_ci` with MySQL v8: https://x.com/reinink/status/1265349317314969605?s=20

Fix incorrect collation for MySQL 8

---

config/database.php

Reverts laravel/laravel#6239
It seems this collation is not supported for MariaDB:  
https://mariadb.com/kb/en/supported-character-sets-and-collations/
I also tested it with Laravel Sail + MariaDB and it doesn't work:
In the original PR, @binaryfire asked if it possible to add a new config section for mariadb.

Revert "Fix incorrect collation for MySQL 8"

---

config/database.php

I tested with Laravel Sail both MySQL and MariaDB both seem to accept the null value and then each use their own default collation.
Here  what I did:
<details><summary>MySQL</summary>
<p>
```
laravel new mysql-collation-test
cd mysql-collation-test
php artisan sail:insall
sail up
sail artisan migrate
sail artisan db
SHOW VARIABLES LIKE 'collation%';
```
Result:
```
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_0900_ai_ci |
| collation_database   | utf8mb4_0900_ai_ci |
| collation_server     | utf8mb4_0900_ai_ci |
+----------------------+--------------------+
3 rows in set (0.00 sec)
```
</p>
</details> 
<details><summary>MariaDB</summary>
<p>
```
laravel new …
```

[10.x] Let database handle default collation

---

config/hashing.php

[PHP is increasing the default bcrypt cost](https://wiki.php.net/rfc/bcrypt_cost_2023) to either 11 or 12 to keep up with increases in computing, so we should do the same within Laravel. The current default of 10 was set in PHP 11 years ago, which is no longer a suitable default.
12 appears to be the sweet spot between performance and security, [as confirmed by a member of the Hashcat team](https://phpc.social/@tychotithonus@infosec.exchange/111104389164750098). [Symfony uses a cost of 13](https://github.com/symfony/password-hasher/blob/6.3/Hasher/NativePasswordHasher.php#L36C1-L37C1), however that may be too high for some servers.
Due to the way hashing works, there are no backwards compatibility issues - older passwords with lower rounds will still be handled properly, and code that …

[10.x] Increase bcrypt rounds to 12

---

database/factories/UserFactory.php

So that `needsRehashing` doesn't default to `true` on a fresh installation.
created using `php artisan tinker` and then verified:
```php
Hash::make('password');
Hash::check('password', '$2y$12$Z/vhVO3e.UXKaG11EWgxc.EL7uej3Pi1M0Pq0orF5cbFGtyVh0V3C');
```

[10.x] Use 12 bcrypt rounds for password in UserFactory

---

config/sanctum.php

This pull request fixes a simple typo in a recently added comment, as well as change some other words in order to not break the secret rule.

[10.x] Fix typo in the comment for token prefix (sanctum config)

---

composer.json

This pull request fixes build of `dev-master`, and removes tinker for now, while Symfony 7 is not supported on Tinker.

[11.x] Fixes build of `dev-master`

---

database/factories/UserFactory.php

Matches the lower cost for unit testing.

[10.x] Update fixture hash to match testing cost

---

composer.json

PR #6234 updated the configuration but it depends on Sanctum 3.3. This PR avoids installing Sanctum 3.2 with the new config.

[10.x] Update minimum `laravel/sanctum`

---

config/app.php

Binary operators should be surrounded by space a single space.

Redis maintenance store config example contains an excess space

---

database/factories/UserFactory.php

This pull request adds a property description to the new `password` property on user's factory. The reason is simply to ensure consistency that all properties have a comment.

[10.x] Fixes missing property description

---

app/Http/Controllers/Controller.php

This pull request adds the `abstract` keyword on Controller class for Laravel 11.x.

[slim-skeleton-11.x] Adds `abstract` keyword on Controller class

---

app/Models/User.php

This pull request uses generic annotation for `User::casts` return type. It's just to be consistent with the rest of the skeleton + starter kits that are all of them using this type of return type in arrays.

[slim-skeleton-11.x] Uses generic annotation for `User::casts` return type 

---

tests/Feature/ExampleTest.php

I think it's a better way for Laravel 11.x concepts

Use `assertOk()` instead of `assertStatus(200)` in tests

---

phpunit.xml

This pull request fixes the tests failing due the following error:
```
1) Tests\Feature\ExampleTest::test_the_application_returns_a_successful_response
Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from `cache` where `key` = laravel_cache_illuminate:foundation:down limit 1)
```
Replaces https://github.com/laravel/laravel/pull/6296.

[11.x] Fixes tests failing due database not available

---

phpunit.xml

This pull request fixes `phpunit.xml`'s environment variable, as we are now using `CACHE_STORE` instead of `CACHE_DRIVER`.

[11.x] Uses `CACHE_STORE` instead of `CACHE_DRIVER`

---

tests/Feature/ExampleTest.php

This pull request puts back the `assertStatus(200)` for the simply fact that `assertStatus(200)` speaks to all developers, while `assertOk` is Laravel specific. Also, if we were to `assertOk`, all the stubs (including ones used on starter kits) need to be updated.

[10.x] Reverts `assertOk` change

---

composer.json
package.json

This pull request concerns L11, and updates all versions in `composer.json` for aesthetic reasons. Primarily to display the latest versions of those packages in the `composer.json` file.
In addition, it *always* use the pattern `Major.Minor` for all requirements. I've kept 1.6.3 for `axios`, because: https://github.com/laravel/laravel/pull/6306.

[11.x] Bumps versions on `composer.json`

---

composer.json

This pull request re-adds Laravel Ignition, after I've added support to L11 on it.

[11.x] Re-adds Laravel Ignition

---

package.json

[Another 2 vulnerabilities have been fixed](https://github.com/axios/axios/releases/tag/v1.6.4) (hopefully these PRs are of use to Laravel)
- `formToJSON` prototype pollution vulnerability ([#6167](https://github.com/axios/axios/issues/6167)) ([3c0c11c](https://github.com/axios/axios/commit/3c0c11c))
- Security vulnerability in follow-redirects ([#6163](https://github.com/axios/axios/issues/6163)) ([75af1cd](https://github.com/axios/axios/commit/75af1cd))

[10.x] Update Axios to latest version

---

artisan
bootstrap/app.php
public/index.php
routes/console.php
routes/web.php

Hi everyone! This pull request proposes a small change the PHP comments in our skeleton. They've been around for a while, and we're all pretty used to them. But, I'm curious about your thoughts on reshaping our docs to align more with the style used in "laravel/framework:" (and in any other repository really), while simultaneously do the three-character rule.
Here is an example:
Not that, I am not fully convinced; however, if this pull request gets merged, I will go around to the other repositories and adjust the PHP comments accordingly via PR.

[11.x] Simplify PHP comments

---

composer.json

there was a BC break in PHPUnit https://github.com/sebastianbergmann/phpunit/issues/5690

Fix PHPUnit constraint

---

config/mail.php
config/session.php

Looks like this got missed during the slimming exercise - see PR #6301 from `10.x`
If it's been purposely omitted, `roundrobin` is still mentioned in the comment.
https://github.com/laravel/laravel/blob/708fdb1a36fd4567a2b7fd7557436536005fe4d2/config/mail.php#L33

[11.x] Add missing roundrobin transport driver config

---

config/mail.php

Hi,
It took me forever to figure out what's suddenly wrong with my Google SMTP Relay service mail sending. After a few hours on Google support and additional googling I came across this, and it actually works:
[Laracasts forum subject](https://laracasts.com/discuss/channels/laravel/laravel-incorrectly-handling-ehlo-for-smtp-from-artisancli-issues-with-gmails-smtp-relay-resolved)
Pretty much other clients disregard this and only Google takes it into account (don't know why tho).
Without it you receive something like this when trying to send mail:
```
Expected response code "250" but got code "421", with message "421-4.7.0 Try again later, closing connection. (EHLO)
421-4.7.0  For more information, go to
421 4.7.0  https://support.google.com/a/answer/3221692 …
```

Updated SMTP mail config to use a valid EHLO domain

---

config/filesystems.php
config/logging.php

I noticed that the word `Drivers` appears inconsistently in the config files' PHPDoc, sometimes as camel case and sometimes in lowercase.
For consistency, I changed all instances of `Drivers` to `drivers`.
---
Other occurrences of lowercase `drivers` can be found here:
https://github.com/laravel/laravel/blob/b6d55576d1c9fcf15adebc76bcb6d8cb476a4418/config/app.php#L117
https://github.com/laravel/laravel/blob/b6d55576d1c9fcf15adebc76bcb6d8cb476a4418/config/cache.php#L29
https://github.com/laravel/laravel/blob/b6d55576d1c9fcf15adebc76bcb6d8cb476a4418/config/queue.php#L102

Format the first letter of `drivers`  to lowercase

---

config/cache.php

I wasn't immediately obvious that the lock table name could be changed because the option isn't exposed by default in the configuration.
Since [I had to do a bit of digging](https://github.com/laravel/framework/blob/02a0b5f6f83b13ea750f959364aefa324441a354/src/Illuminate/Cache/CacheManager.php#L212-L231) to find the option, I thought this would be a welcome addition.

Expose lock table name

---

composer.json

Laravel Upgrade Doc suggest to upgrade [nunomaduro/collision version to ^8.1](https://github.com/laravel/docs/blob/358fd26b3a81359b6e5f54d263f50083e82f525b/upgrade.md?plain=1#L74) but default laravel/laravel composer.json version is ^8.0. That's the reason i submitted this PR.
Thanks

[11.x] Collision Version Upgrade

---

app/Models/User.php

Based on this https://github.com/laravel/framework/pull/52005, we always need to add a generic notation to make PHPStan pass. 
If we can't add PHPStan, we should at least add a doc-block to ensure the code passes without issues. This will also help developers learn how to define it properly. Even though some may already know, I’ve received questions from a few developers on how to resolve this specific PHPStan error.
I'm simply adding the following in the `User` model:
```php
/** @use HasFactory<\Database\Factories\UserFactory> */
use HasFactory, Notifiable;
```

[11.x] factory-generics-in-user-model

---

resources/views/welcome.blade.php

Every image should have an alt tag for accessibility reasons, but this one did not, so this commit aims to add the missing one.

Update welcome.blade.php to add missing alt tag

---

composer.json

This PR introduces a quality of life improvement by adding `"$schema": "https://getcomposer.org/schema.json"` to `composer.json` in order to have autocompletion in editors like VS Code, PhpStorm etc.

Add schema property to enhance autocompletion for composer.json

---

composer.json

We might bump the framework version to `11.31` to address https://github.com/laravel/framework/security/advisories/GHSA-gv7v-rgg6-548h.

[11.x] Bump framework version

---

app/Models/User.php

the docblock in `HidesAttributes` was updated in #42512, so this child class should be using the same.
otherwise PHPStan throws a "PHPDoc type array<int, string> of property App\Models\User::$hidden is not covariant with PHPDoc type list<string> of  property Illuminate\Database\Eloquent\Model::$hidden" error

[11.x] match `HidesAttributes` docblocks

---

app/Models/User.php

With the new version of PHPStan (2) / Larastan (3) you now get the "type array<int, string> is not covariant with type list<string> of overridden property" error on anything above level 2 (default/proposed is 5) on a clean project.
https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants#list-type
The list type is also supported by Psalm: https://psalm.dev/docs/annotating_code/type_syntax/array_types/

[11.x] Narrow down array types to lists

---

.gitignore

Hey There, 
I made this pull request for the following. For now if i perform the  `php artisan lang:publish` command i will get the the default english translation files from the framework. 
But if i want to a new language and want to use JSON file. the auth.json file will not be added to my commit due to the `auth.json` entry in the `.gitignore` file. This commit will allow to commit the ´´lang/nl/auth.json´ file but still isgnore the  `auth.json` file.

Update .gitignore to not ignore auth.json in the lang directory.

---

resources/views/welcome.blade.php

**Issue**:
Warning in Tailwind CSS Version 4 Beta When Using the + Operator Without Surrounding Whitespace
**Description:**
When the + operator in Tailwind CSS does not have whitespace on both sides, it triggers a warning in Tailwind CSS version 4 Beta.
```
▲ [WARNING] The "+" operator only works if there is whitespace on both sides [invalid-calc]
<stdin>:371:42:
371 │ .w-\[calc\(100\%\+8rem\)\]{width:calc(100%+8rem);}
╵                                           ^
▲ [WARNING] The "+" operator only works if there is whitespace on both sides [invalid-calc]
<stdin>:831:695:
831 │ ...100\%\+8rem\)\]{width:calc(100%+8rem);}.w-auto{width:auto;}.w-...
╵                                   ^
```
** To Reproduce:**
Use the `+` operator in a calc function without adding whitespace around …

fix css whitespace invalid-calc

---

public/.htaccess

In [.htaccess](https://github.com/laravel/laravel/blob/11.x/public/.htaccess) file right now we have rewrite rule to preserve **Authorization** header. That commit exists in .htaccess file [since 2016](https://github.com/laravel/laravel/commit/85e8d21ef2320977d6f205ef793dc595ed5638d3), which was [later updated](https://github.com/laravel/laravel/commit/8d1d1e1b94d7b1aedd94416a361db0fa499d0a73). 
Laravel uses [X-XSRF-TOKEN](https://laravel.com/docs/11.x/sanctum#csrf-protection) for session based authentication in API and just like **Authorization** header is sometimes removed by some of the server configurations (Typically on shared hosting) **X-XSRF-TOKEN** is also removed and to properly implement session based authentication with Laravel API, the header needs to be preserved.
I came to …

Preserve X-Xsrf-Token header from .htaccess

---

routes/console.php

See the diff that introduced this: https://github.com/laravel/laravel/commit/dd60315e9ad725c99d883a668f35cfaa6a1aa8e3#diff-c96ad2c3c018fea7d8ea9667a55e8e2fe309bc2a0df81945ab0a65493a4486f0
The console schedule section was removed, but the commit used final line of the file instead of the correct line from the console commands section. This was confusing for a newcomer to both PHP and Laravel :)

Remove extra hourly() method in console.php

---

artisan
public/index.php

This PR adds explicit type hints for the $app variable in artisan and public/index.php using PHPDoc comments.
Why?
-  Improves static analysis by tools like PHPStan and PHPStorm, allowing them to correctly infer the type.
- Prevents unnecessary warnings or incorrect suggestions in IDEs.
- Enhances code readability by making it clear that $app is an instance of Illuminate\Foundation\Application.
**Impact**
- No runtime behavior changes.
- Does not introduce breaking changes.
- Strictly improves developer experience.
**Testing**
Since this change only affects static analysis, no functional tests are included. However, I can set up PHPStan within the test suite if desired.

Improve static analysis by adding type hints for $app in artisan and public/index.php

---

composer.json

In preparing for the Laravel 12.x Shift, I noticed the dependency on `nunomaduro/collision` was removed. But I don't see it within `laravel/framework` or another first-party dependency. So I'm assuming maybe this was accidently removed when resolving [this merge conflict](https://github.com/laravel/laravel/commit/295bdfeee961c760425a392942273febe1eb6cc9), and should be re-added. 😅

Re-add nunomaduro/collision

---

.github/workflows/tests.yml

This PR changes the test runner for the github action to `php artisan test`
The included github testing action executes `./vendor/bin/phpunit` but when pest is chosen, this results in an error. 
I know it's easy to fix (and the error message tells you exactly what to do, that is, run `./vendor/bin/pest`), but wouldn't it be nicer if it would just work out of the box?
No runtime behavior changes
Compatible with existing Laravel applications.

Make the github test action run out of the box independent of the choice of testing framework

---

routes/console.php

This PR adds a type hint for `$this` in `routes/console.php`, ensuring better IDE support and improved static analysis when working with console commands.
- **Improves Developer Experience**: IDEs can now provide autocompletion and proper type inference for `$this` within console command closures.
- **Enhances Static Analysis**: Helps tools like PHPStan understand the type of `$this`, reducing potential false positives in type checks.
- **Better Code Readability**: Explicitly declaring `$this` as an instance of `Illuminate\Console\Command` makes the code easier to understand for new developers.
- No runtime behavior changes; this is a documentation-level improvement.
- Fully backward compatible with existing Laravel applications.
Note: This replaces #6554, which I closed before realizing …

feat: add type hints for $this in routes/console.php

---

config/logging.php

This PR updates the structure of the `stderr` logging channel configuration to place the `handler` option before its constructor parameters `with`.
Why?
Laravel's documentation states:
> "Optionally, any constructor parameters the handler needs may be specified using the with configuration option."
Reordering these options makes it clearer that `with` provides parameters for `handler`, improving readability and maintainability.

[12.x] Refactor: Structural improvement for clarity

---

resources/css/app.css

I think that the `@source` for `.vue` is not important because if we need to use Vue we will use the Vue starter kit

[12.x] Remove Unnecessarily @source

---

package.json

Not sure how high we want to go, but the only unaffected versions are
6.0.12  (latest version of 6.0)
6.1.2 (latest release of 6.1)
6.2.3 (latest release)
Security issue: https://github.com/vitejs/vite/security/advisories/GHSA-x574-m823-4x7w

Bump vite from 6.0.11 to 6.2.3 - Vulnerability patch

---

package.json

Another CVE was published for Vite recommending updating `<=6.2.3` to `6.2.4` or greater. Not sure if this affects Laravel, but better save that sorry.
https://github.com/vitejs/vite/security/advisories/GHSA-4r4m-qw57-chr8

Bump vite from 6.2.3 to 6.2.4

---

README.md

**Description:**
This PR updates a few URLs in the README.md to remove unnecessary trailing slashes. This helps maintain a clean style. All updated URLs still point to the correct destinations.

[12.x] Clean up URL formatting in README

---

config/session.php

According to: https://github.com/laravel/laravel/commit/2d8f562092a376cf80d07e3e4583bb8463bb51bf I think we need to remove `apc` also from here.

[12.x] Remove apc

---

config/auth.php

PhpStorm's Natural Language module recommends this change to a countable noun, which happens to be exactly 6 characters long, so as to not affect the overall length of the line while still making it ever-so-slightly more parseable.

Minor language update

---

.gitignore

Description
---
I think the `*.log` already covers `yarn-error.log` and `npm-debug.log`, Since `*.log` matches any file ending in `.log`, including those two, explicitly listing them is unnecessary unless they need special treatment.

[12.x] Reduce redundancy and keeps the .gitignore file cleaner

---

package.json

Adds Vite 7 support. Locking to Vite version `^7.0.4` as there is a minor bug in the previous v7 versions.

Add Vite 7 support

---

composer.json

This is a suggestion to help solve an issue with the OpenTelemetry PHP SDK package but may also help other packages from falling into the same trap.  There is an open issue here: https://github.com/open-telemetry/opentelemetry-php/issues/1673
Laravel adds a PHP callback script to the post-autoload-dump event in composer.json
https://github.com/laravel/laravel/blob/12.x/composer.json#L36
```json
"scripts": {
"post-autoload-dump": [
"Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
```
https://getcomposer.org/doc/articles/scripts.md#scripts
When Composer runs PHP callback scripts it means you are inheriting all the dependencies of the composer.phar.  This is not normally an issue if the script is fairly simple however the Laravel postAutoloadDump function calls the Composer …

Change composer post-autoload-dump script to Artisan command

---

config/database.php

Allows Redis connections to be retried automatically. 
The additional configuration is only applied if the `phpredis` extension is loaded. It depends on constants that are not available without it — for users running other cache drivers, or running Predis, nothing changes.
`decorrelated_jitter` is used by default to avoid "retry storms" — [Here's an AWS article](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)
With the default configuration, retry delays would be ~300ms, ~600ms, ~1000ms, for a ~2 second total retry window.
This is a bit of a beefy config, mostly because of that `match` statement — maybe we could pass strings and parse them on `framework` — that'd also solve having to be careful with calling the `Redis` namespace

[12.x] Add default Redis retry configuration
