config/app.php, config/cache.php, config/database.php, config/queue.php, config/session.php
=> [5.0]Modify the wording of env() default values

resources/views/app.blade.php
Removing the Bootstrap comment referencing the CSS removed in 26fce312c5e5d51ae32e97128a06599b7cfd2d21.
=> Remove comment from duplicate bootstrap instance.

composer.json
=> copy .env file as after create project

app/Providers/EventServiceProvider.php
Fixes use Dispatcher Contract on EventServiceProvider.
=> [5.0] Fix app event service provider contract

gulpfile.js
updated elixir description in gulpfile from sass to less to avoid confusion.
=> updated elixir description in gulpfile from sass to less

app/Providers/RouteServiceProvider.php
This allow to use:
```php
$router->get(...);
$router->post(...);
...
```
In routes.php file
=> [5.0] Allow to use $router in routes file

config/filesystems.php
See https://github.com/laravel/framework/pull/5773 for details.
=> Add support for configuring AWS S3 region.

config/app.php
As per Taylor request here: https://github.com/laravel/framework/pull/7173#issuecomment-71988006
=> Mentioning new config option

config/filesystems.php
added default url type to Rackspace Cloud Files config to match the pr #7409 in laravel/framework
=> config options for larval/framework pr #7409

public/index.php
The run method isn't called anymore.
=> Updated Run The Application comment

app/Http/Kernel.php
Moved to develop branch as requested by Taylor in https://github.com/laravel/laravel/pull/3321
=> [5.1] Add new middleware

readme.md
=> fix downloads svg icon path

app/Http/Kernel.php
=> Revert "[5.1] Add new middleware"

config/mail.php
SES Driver is available and working, this will help make it more obvious to end users.
=> Documented availability of SES mail driver in mail config

package.json
Previous default version was "*"
=> Change package.json so changed to elixir will be non-breaking changes

composer.json
Goes with laravel/framework#8876.
=> Add faker to require-dev

config/cache.php, config/database.php, config/filesystems.php, config/session.php, config/view.php
Some places the path was passed in & some it was being concatenated, so just making it all use the path parameter.
=> Using the path parameter in the path method.

app/Console/Kernel.php, app/Exceptions/Handler.php, app/Http/Kernel.php
Use the ::class notation for class references in app/ folder.
Similar to #3403
=> Use the ::class notation

resources/views/app.blade.php
=> Update latest CDN

phpunit.xml
Same as https://github.com/laravel/lumen/pull/25
=> Added whitelist to remove warning for upcoming phpunit 4.8

resources/views/errors/503.blade.php, resources/views/welcome.blade.php
<!DOCTYPE> declaration is a must in HTML documents.
=> Fix doctype declarations

resources/views/errors/503.blade.php, resources/views/welcome.blade.php
Just to keep things consistent.
=> Use double quotes for html attributes

resources/lang/en/passwords.php
add default language.
Depending on this PR  [laravel/framework](https://github.com/laravel/framework/pull/9498)
=> Add ThrottleLogin localization support

database/factories/ModelFactory.php
allow IDE to help with autocompletion
=> type hint faker generator

.gitignore
This would correspond with https://github.com/laravel/homestead/pull/233
=> Ignore Homestead.json

phpspec.yml
see 58e4045f6d3a3c44796a5d48fdfdce8b2a40282d
=> remove phpspec.yml

resources/lang/en/validation.php
To go along with:
* https://github.com/laravel/framework/pull/9944
* https://github.com/laravel/docs/pull/1753
=> Error message for JSON validation

resources/views/errors/503.blade.php, resources/views/welcome.blade.php
Ensure the default views always use HTTPS for the loading of fonts.
https://github.com/konklone/cdns-to-https#background
=> Use https rather than // for google fonts in default views.

app/Providers/AuthServiceProvider.php
Signed-off-by: crynobone <crynobone@gmail.com>
=> [5.1] Use $this instead of parent.

database/seeds/DatabaseSeeder.php
It's now done in the seeder command: https://github.com/laravel/framework/pull/10474
=> Remove unguard call

config/broadcasting.php
Added the options array to the pusher configuation file, in order to pass in extra options to the Pusher class if needed. This will go hand in hand with a PR request that I am submitting on the `laravel/framework` package as well to update the `BroadcastingManager.php` to pull in those configurations.
First pull request, long time user. Appreciate everything you're doing and if it doesn't get merged, no hard feelings lol.
=> Added options to the broadcasting pusher configuration file.

app/User.php
> Lists of implements MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one interface per line.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#41-extends-and-implements
=> PSR-2 formatting of User model?

config/mail.php
I usually start every project by doing this so it would be nice to have it already setup out of the box as different environments typically have different mail config settings.
=> Set Mail pretend config from .env

composer.json
Goes with https://github.com/laravel/framework/pull/10938.
=> [5.2] Added two symfony deps to require-dev

package.json
Laravel elixir is now at version 4
=> Bump Laravel Elixir version

resources/lang/en/passwords.php
=> Wording "Reminder" => "Reset"

config/queue.php
Updated queue config file to match sqs prefix changes in the framework
=> added queue prefix to match the framework

config/queue.php
=> Revert "added queue prefix to match the framework"

app/Http/Middleware/Authenticate.php
=> Create a new middlware instance instead of filter.

public/.htaccess
Added conds and rules to .htaccess file to handle Authorization Header that are necesary to use Token Guard Authorization.
=> Handle authorization header

config/database.php
In reference to https://github.com/laravel/framework/pull/12147
=> Added default engine in configuration

database/seeds/DatabaseSeeder.php
Rename commented default seeder call to be consistent with official docs
https://laravel.com/docs/5.2/seeding
=> Rename commented default seeder call

.env.example, config/database.php
Hello,
The attached paramater is required when working with MySQL homestead on a Windows enviroment.
Please take this pull request into consideration.
Regards,
Dan C.
=>  Added DB_PORT as a default enviroment variable 

config/mail.php, config/services.php
Related to the SparkPost's support PR: https://github.com/laravel/framework/pull/12579
=> Added SparkPost config

app/Http/Middleware/Authenticate.php
Using this, you'd be able to allow access to a single route for multiple guards:
```php
Route::get('foo', 'Foo@foo')->middleware('auth:web,api');
```
=> Allow passing multiple gaurds to the auth middleware

package.json
Just giving a bump to the Elixir and Gulp dependencies.
=> Bump package versions

app/Http/Controllers/Controller.php, app/Http/Kernel.php
Supports this: https://github.com/laravel/framework/pull/12913
=> Add support for the authorize middleware and AuthorizesRequests trait

.env.example, composer.json, database/factories/ModelFactory.php, phpunit.xml
People are still making new 5.1 apps because of the LTS branding, so it makes sense for us to ensure new 5.1 apps have the best defaults and work correctly.
For that reason, I suggest we backport these changes.
=> [5.1] Backport various changes

.gitattributes
There are not LESS files, only Sass.
=> Switch to `.scss`

config/cache.php
Adds config for persistent connections, SASL authentication, and custom options
=> [5.3] Add config for new Memcached features

package.json
Unless there is a reason why not?
=> Use Bootstrap 3.3

config/session.php
Complements laravel/framework [PR #13403](https://github.com/laravel/framework/pull/13403)
=> [5.3] Adds configuration for session cache store

app/Http/Kernel.php
Goes with https://github.com/laravel/framework/pull/13548. I've also positioned this in such a way as to maximize performance by performing the bindings as late as possible.
=> [5.3] Added the new bindings middleware

app/Exceptions/Handler.php, app/Http/Middleware/Authenticate.php
This PR is part of [this change](https://github.com/laravel/framework/pull/13651), so that we can [unify unauthenticated responses](https://github.com/laravel/framework/pull/13113).
=> [5.3] Make the Authenticate middleware throw an AuthenticationException

.env.example, config/app.php
This config option ties in with changes in https://github.com/laravel/framework/commit/fbd6e7793766c4b3671328b80fb315391f11a3ed that were tagged in [v5.2.35](https://github.com/laravel/framework/releases/tag/v5.2.35) of the framework.
=> Add application log level configuration

config/queue.php
Considering [this issue](https://github.com/laravel/framework/issues/14160)
=> expire jobs after 90 seconds

composer.json
=> Modify post-root-package-install script.

app/Http/Controllers/Auth/LoginController.php
=> [5.3] fix wrong spelling

resources/views/welcome.blade.php
=> Revert "Removes padding on html/body to kill the scrollbar"

resources/assets/js/app.js
Reference to Pull Request #3871
=> Use const instead of var in Vue instance

app/Exceptions/Handler.php
Inspired by: https://twitter.com/reinink/status/764093723680452608
=> [5.2] Add TokenMismatchException to the dontReport array

config/app.php
Minor change to stay consistent
=> Sorted the Application Service Providers alphabetically

public/web.config
Can the web.config from Laravel 5.2 be added back to the 5.3 public folder? It helps in the setup of a new project on Windows.
Thanks!
=> Add web.config for IIS

resources/lang/en/validation.php
See https://github.com/laravel/framework/pull/15209.
=> Add missing translation for `mimetypes` validation

package.json, resources/assets/js/bootstrap.js
Propose updating Vue Resource.
Will require changing the way we set X-CSRF-TOKEN header in bootstrap.js
This seems to be compatible with Laravel Passport. [Documents Pull Request](https://github.com/laravel/docs/pull/2695)
=> Update Vue Resource

config/database.php
Same as https://github.com/laravel/laravel/pull/3955, but on `develop` and without the whitespace :D
=> Added `database.redis.client` configuration

gulpfile.js, package.json, resources/assets/js/app.js, resources/assets/js/components/Example.vue
Minor updates to deal with deprecations in Vue.js 2. 
I've [submitted an accompanying PR for Passport](https://github.com/laravel/passport/pull/117).
=> Update to use Vue.js 2.0.x

database/factories/ModelFactory.php
So that an IDE can autocomplete the calls.
=> Add typehint for Factory

app/Http/Controllers/Auth/RegisterController.php
Added fullpath import for the validator facade.
=> Use fullpath for validator facade

routes/web.php
Changed web routes description to make it easy to undestand
=> Changed web route description

routes/web.php
Formatted web routes description for better understanding
=> comment formatting

config/mail.php
=> Mail Config

app/Providers/RouteServiceProvider.php
=> [5.4] Use path for group directly

webpack.mix.js
Is a good practice use `const` with `require` and more elegant use destructuring assignment.
=> Use const and destructuring assignment

composer.json
Only autoload the tests namespace in dev.
=> Update composer.json to contain autoload-dev for Test namespace

composer.json
=> Revert "Append '@' to let composer resolve PHP executable"

package.json
Updated laravel-mix version in `package.json` file.
=> Updated laravel-mix version

package.json
https://github.com/kentcdodds/cross-env/commit/aae44dff49494912a76423a7e45d3d1afd630e4a
=> [5.4] Fix cross-env bin path

package.json
Upgrade laravel-mix from 0.8.1 to 0.8.3 after successful testing
=> Upgrade laravel-mix to 0.8.3

composer.json
Composer allows us to optimize the autoloader using the --optimize flag or shortly -o.
=> Composer -o

.gitattributes, CHANGELOG.md
Make it easier to keep track of changes in the `laravel/laravel` repository.
=> Added changelog

app/Http/Controllers/Auth/RegisterController.php
We dont allow arrays here - so validate for it.
Might help raise awareness for people with situations like: https://github.com/laravel/framework/issues/18697
=> Add string to validation

app/Http/Controllers/Auth/LoginController.php
Assign guest middleware to LoginController using documented way https://laravel.com/docs/5.4/controllers#controller-middleware to avoid confusing with $options array values meaning.
=> More clear way to assign middleware in controller

config/queue.php
this PR goes along with https://github.com/laravel/framework/pull/18860
=> add queue prefix value

composer.json
=> Use current PHP version instead of using PATH

resources/views/welcome.blade.php
Similar as laravel/framework#19405, but for the welcome view (the other was for the Auth scaffolding).
Also, resubmission of #4282, as Taylor confused it with laravel/framework#19405.
=> Dynamic changing locale

package.json
Upgrade `axios` and `cross-env`
=> Upgrade axios and cross-env packages

app/Http/Controllers/Auth/RegisterController.php
=> [5.4] Fix docblock.

resources/views/welcome.blade.php
This makes the links consistent with the ones in https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Console/stubs/make/views/layouts/app.stub
=> Change hardcoded urls to named routes

package.json
=> Revert "don't need it"

config/app.php
I know it is a small thing but it's driving me crazy!
=> Fix in comment in config/app.php

config/cache.php
Make cache prefix like session cookie.
=> Update cache prefix. 

config/database.php
=> Revert "Use database_path helper for sqlite database filename specified in .env"

readme.md
Since the readme is the first thing many people see when visiting any repository, I've always been of the mindset that it's important for it to be as perfect as possible. I admire the obvious time and effort that has been put into it thus far. These are just a few minor changes to wording that I feel improve the way it reads. I've provided my logic for each change via comments on the corresponding lines.
=> Reword the readme slightly and link the email address

readme.md
According to - https://laracasts.com/stats
Related: https://github.com/laravel/framework/pull/21213
:octocat:
=> Update Laracasts statistics

package.json
Updated jquery in `package.json`.
=> Update jquery in package.json

readme.md
Added us in a sponsor section by following instructions we received.
=> add sponsor

package.json
Updated `cross-env` in `package.json` and just use **`MAJOR.MINOR`** like `jQuery`, `axios`, `laravel-mix`, etc
=> Updated cross-env in package.json

readme.md
I hope you mind me remove redundant language just to make it shorter. Thanks.
=> Removing redundant language

readme.md
This PR makes the Vehikl link more :closed_lock_with_key: 
:octocat:
=> Make Vehikl link HTTPS

readme.md
=> Make links HTTPS

config/queue.php
=> Update SQS config

package.json
=> Update bootstrap version

.gitignore
Add /.vscode to .gitignore file to prevent commiting content of that folder to git repo.
=> Add VSCode to gitignore file

composer.json
This will stop people screwing up installations.
=> [5.6] Use composer platform config

composer.json
This will stop people screwing up installations.
=> [5.5] Use composer platform config

composer.json
Reverts laravel/laravel#4573
Discussion in this other PR only please (to keep it in one place rather than split): https://github.com/laravel/laravel/pull/4579
=> Revert "[5.5] Use composer platform config"

config/filesystems.php
Reference: [#23308](https://github.com/laravel/framework/pull/23308)
=> Add SFTP to supported storage drivers

resources/lang/en/validation.php
Sidecar for https://github.com/laravel/framework/pull/23475.
=> [5.6] Add message for "Not Regex" validation rule

config/hashing.php
This is relation for the PR [5.6] Add hashing configuration #23573 on the laravel/framework
=> [5.6] Add hashing configuration

readme.md
Thank you for creating such an amazing framework!
We've benefited tremendously from both the source code and the amazing community which continues to build around Laravel. We really appreciate your hard work and are thrilled to be able to support you in this small way.
The future for Laravel looks pretty bright :)
=> Added Invoice Ninja to the readme

readme.md
Cubet is an official sponsor of Laravel- https://laravel.com/partners
Added an entry to list Cubet under Laravel Sponsors.
=> Added Cubet as a Sponsor

app/Http/Middleware/TrustProxies.php
=> Request::HEADER_X_FORWARDED_ALL is an integer

readme.md
Hello! Circumstances are forcing me to do a lot of shuffling/reorganizing, and I'm going to need to drop (hopefully temporary) my Patreon pledge.  There's nothing worse than a freeloader, so this is me preemptively removing my link from the README. 
Keep up the great work with Laravel though!
=> Removing Patreon Link

resources/lang/en/validation.php
It also accepts underscores as valid signs as explicitly stated in the docs and source code so I believe it would be best to also add it to the validation message.
=> [5.6] Fix alpha_dash

app/Http/Middleware/VerifyCsrfToken.php
Matches the new option from https://github.com/laravel/framework/pull/24726
=> [5.7] Add addHttpCookie to VerifyCsrfToken

resources/views/welcome.blade.php
Updated the font to Nuntio from Raleway
=> Changed font to new one

database/factories/UserFactory.php
the email_verified_at column value is used to determine whether a user has verified her account.
=> Seeded users should be verified by default

composer.json
I like seeing the colors, makes it easier to scan.
=> Preserve colors

resources/views/welcome.blade.php
In relation to https://github.com/laravel/framework/pull/25556.
=> [5.7] Check if register route is enabled.

resources/views/welcome.blade.php
Make the lang attribute similar to 
https://github.com/laravel/framework/blob/2dd96e9e5251e0970fc8b003c5b86e0114c22331/src/Illuminate/Auth/Console/stubs/make/views/layouts/app.stub#L2
See the origin of this change
https://github.com/laravel/framework/pull/24392
=> [5.7] Update lang attribute

config/database.php
This is related to https://github.com/laravel/framework/pull/25867 if it is accepted.
=> [5.7] Update database config

config/services.php
See https://github.com/laravel/cashier/pull/565
=> [5.7] Add new Stripe webhook config values

CHANGELOG.md
=> [5.7] Added changelog for v5.7.0

app/Http/Controllers/Auth/RegisterController.php
Changed the syntax for the validation to be more aligned to the proposed way of implementing custom validations in the docs: https://laravel.com/docs/5.7/validation#custom-validation-rules
=> changed syntax for validation

resources/lang/en/validation.php
Related to [#26135 in laravel/framework](https://github.com/laravel/framework/pull/26135)
=> Add message for UUID validation rule

resources/lang/en/validation.php
The main idea was to change
```diff
- ...such as E-Mail Address instead...
+ ...such as "E-Mail Address" instead...
```
because it makes more sense that way. But then we have to change all the text to keep the correct indentation rules :)
=> [5.7] Improve docs

.gitignore
vscode has it's own ignore and so should NetBeans IDE
=> [ALL] gitignore for NetBeans IDE

resources/js/app.js
As per @reinink's suggestion, clean this helper into a single line.
=> [5.7] Clean up auto register Vue components

resources/lang/en/validation.php
https://github.com/laravel/framework/pull/26584
=> [5.7] Add date_equals validation message

resources/lang/en/validation.php
See https://github.com/laravel/framework/pull/26612
=> [5.7] Add language entry for starts_with rule

resources/views/welcome.blade.php
I'm not sure if that would be too much. But it's an attempt to add the new Laravel blog to the link list.
=> [5.7] Adds the Laravel blog to the link list

config/logging.php
In conjunction with laravel/framework/pull/27308
=> [5.7] Hint for lenient log stacks

database/factories/UserFactory.php
https://github.com/laravel/framework/pull/26898
=> Use Str::random() instead of str_random()

storage/framework/.gitignore
=> Revert "[5.7] Ignore testing folder on storage/framework"

app/Http/Middleware/RedirectIfAuthenticated.php
=> Revert "[5.8] Modify RedirectIfAuthenticated middleware to accept multiple guards"

resources/js/app.js
This tiny patch adds missing commas to the app.js file.
=> Fix unterminated statements

readme.md
=> Added Hyper Host sponsor

readme.md
Minor update to the readme file with the current number of @laracasts video tutorials.
@taylorotwell, you are the man.
This is my first pull request, so I wanted to honor @JeffreyWay with it for teaching me the ropes. I greatly appreciate both of you making the rest of us into web artisans with Laravel!
=> Update readme with Laracasts count

database/factories/UserFactory.php
See https://github.com/laravel/framework/pull/28188
=> Add IDE typehint to UserFactory

readme.md
> Boost you and your team's skills
should be
> Boost your and your team's skills
=> [5.9] Minor grammar fix in readme.md

.gitattributes
=> Revert "Exclude StyleCI config from exported files"

config/database.php
https://github.com/laravel/framework/pull/28308
=> [5.8] Update database config relating to Url addition

resources/lang/en/validation.php
This is in conjunction with PR [#28455](https://github.com/laravel/framework/pull/28455) to the framework.
=> [5.8] Add ends_with validation message

config/database.php
Regarding laravel/framework#28612
=> [5.8] Added support for new redis URL property in config/database.php

app/Http/Kernel.php
This is a resubmit of #5056 and PR-ed on the develop branch as is was requested.
=> [5.9] Add ThrottleRequests to the priority array

readme.md
Commit updates the number of available Laracasts videos. As of this writing there are 1506 videos.
=> [5.8] Update number of Laracasts videos

config/services.php
These now ship with a dedicated config file for Cashier.
=> [5.8] Remove Stripe config settings

config/hashing.php
=> Revert "[6.x] Set argon defaults to prevent password_hash(): Memory cost is outside…"

readme.md
Happy to be able to be a supporter
=> [6.x] Added OP.GG sponsor

phpunit.xml
This allows an IDE to do auto completion, and show any errors in the configuration
=> Add xml schema to phpunit

database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2019_08_19_000000_create_failed_jobs_table.php
From https://github.com/laravel/framework/commit/a0c73f0c5dab7a8a943ad57297dbdfec34e89b48
=> [7.x] Implement new primary key syntax

app/Exceptions/Handler.php, config/session.php
Pairs with https://github.com/laravel/framework/pull/30610.
=> [7.x] Switch to Symfony 5

resources/lang/en/passwords.php
Keep the alphabetical order of the validation messages.
=> [6.x] Consistent alphabetical order

app/Http/Kernel.php, app/Providers/AuthServiceProvider.php
Will be made possible by https://github.com/laravel/framework/pull/30877.
=> [7.x] Remove register in auth provider

database/factories/UserFactory.php
This was caused by a regression in StyleCI that is fixed now.
=> [6.x] Revert "Apply fixes from StyleCI"

config/filesystems.php
https://github.com/laravel/framework/pull/31355
=> [7.x] add `links` option to filesystem config

config/cache.php
This documents the new configuration option from https://github.com/laravel/framework/pull/31295
=> Add serialize option to array cache config

database/seeds/DatabaseSeeder.php
https://github.com/laravel/docs/pull/5920
=> [7.x] Consistent filename

config/filesystems.php
This fixes the issues described in the PR below and just lets people choose which one they like to use. If this gets merged I'll also merge this into master.
https://github.com/laravel/laravel/pull/5267
=> [6.x] Add both endpoint and url env variables

phpunit.xml
See: https://github.com/laravel/framework/blob/7.x/phpunit.xml.dist#L14
=> [7.x] Normalize Style

config/mail.php
Reference: https://github.com/laravel/framework/pull/32616
=> [7.x] Allow configuring the auth_mode for SMTP mail driver

composer.json
Bump the default fruitcake/laravel-cors to the current major. No other changes required.
=> Bump fruitcake/laravel-cors

resources/views/welcome.blade.php
https://developers.google.com/fonts/docs/css2
=> [8.x] Use the new Google Fonts API

resources/views/welcome.blade.php
https://developers.google.com/fonts/docs/css2
=> [6.x] Use the new Google Fonts API

app/Http/Middleware/RedirectIfAuthenticated.php
See https://github.com/laravel/laravel/pull/5392#issuecomment-689396418
=> [8.x] Fix docblock for variadic parameter

database/seeders/DatabaseSeeder.php
makes it easy to just uncomment when tinkering around
=> [8.x] Fully qualified user model in seeder

phpunit.xml
=> [8.x] Revert "[8.x] Fix PHPUnit bool server consts result in null"

app/Models/User.php
This will minimize the lines reported as changed in git or other version control systems when adding Jetstream to a new project. [Link](https://github.com/laravel/jetstream/blob/1.x/stubs/app/Models/User.php) for formatting comparison.
=> [8.x] Update User Model to Match Jetstream Formatting

app/Http/Middleware/RedirectIfAuthenticated.php
stemming from https://github.com/laravel/framework/pull/34224
=> [8.x] type hint the middleware Request

.env.example
Added 'LOG_LEVEL' env variable in .env.example to be consistant with the change in [#5442](https://github.com/laravel/laravel/pull/5442)
=> [8.x] Added 'LOG_LEVEL' env variable in .env.example

resources/lang/en/validation.php
See: https://github.com/laravel/framework/pull/34788 and https://github.com/laravel/framework/pull/34858
=> [8.x] Add 'multiple_of' translation

composer.json
See https://github.com/laravel/framework/pull/34928
=> [6.x] Bump minimum PHP version

composer.json
Removing blocking dependencies for now.
=> [9.x] Allow for composer install on Laravel 9

composer.json
Switch to the new https://github.com/FakerPHP/Faker library.
=> [6.x] Update Faker

resources/views/welcome.blade.php
This was messing up blade formatting in vscode
=> closed @auth correctly

app/Http/Middleware/TrustProxies.php
Solve the deprecation warning.
=> [8.x] Update TrustProxies.php

composer.json
In addition to the changes on the framework repo.
=> [9.x] Bump to PHP 7.4

resources/views/welcome.blade.php
=> Revert "Change "Login" text to "Log in""

resources/views/welcome.blade.php
Added sans-serif as Fallback Font to the Welcome Page
=> [8.x] Added sans-serif as Fallback Font

config/queue.php
Hi,
This tiny change makes changing driver queue name more seamless out of the box.
Thanks
=> Use same default queue name for all drivers

resources/lang/en/validation.php
Adding validation rule for https://github.com/laravel/framework/pull/36667
=> [8.x] Add prohibited validation rule

composer.json
This is the only composer.json of all our OS repos atm with a different sequence for its configuration keys.
=> [8.x] Re-order composer.json

database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2014_10_12_100000_create_password_resets_table.php, database/migrations/2019_08_19_000000_create_failed_jobs_table.php
Replacement for https://github.com/laravel/laravel/pull/5585
=> [9.x] Implement anonymous migrations

composer.json
Security advisory: GHSA-4mg9-vhxq-vm7j
=> [6.x] Bump framework version to include SQL server security fix

.editorconfig
- https://github.com/laravel/sail/issues/164
- https://github.com/laravel/sail/pull/165#issuecomment-865190799
=> Fix editorconfig for laravel/sail's docker-compose

composer.json
I propose append and promote use additional tag for publishing js and css assets. And automatically publish them after update packages.
https://github.com/laravel/horizon/pull/1045
https://github.com/laravel/telescope/pull/1105
=> [8.x] Unified asset publishing

resources/lang/en/validation.php
Adding `accepted_if` validation rule message (laravel/framework#38210 laravel/docs#7220).
=> [8.x] Add accepted_if validation rule

composer.json
@driesvints This pull request re-adds collision, as I've just prepared a `develop` branch as `6.x` alias.
=> Re-adds collision

README.md
Added an entry to list WebReinvent under Laravel Sponsors.
=> Add WebReinvent as a Sponsor

resources/lang/en/validation.php
This PR adds the default validation message for the `prohibits` validation
=> [8.x] Added `prohibits` validation message

database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
Updates the class name of the personal_access_tokens table the the anonymous migration class name style
=> Use anonymous migration for personal_access_tokens table

composer.json, tests/Feature/ExampleTest.php, tests/TestCase.php
=> Revert "[8.x] Uses `LazilyRefreshDatabase` by default"

app/Http/Kernel.php, app/Http/Middleware/Authenticate.php, app/Http/Middleware/EncryptCookies.php, app/Http/Middleware/PreventRequestsDuringMaintenance.php, app/Http/Middleware/TrimStrings.php, app/Http/Middleware/TrustHosts.php, app/Http/Middleware/TrustProxies.php, app/Http/Middleware/VerifyCsrfToken.php, app/Providers/AuthServiceProvider.php, app/Providers/EventServiceProvider.php
I hope I've assumed all the types correctly.
=> [8.x] Add types to arrays in boilerplate

database/seeders/DatabaseSeeder.php
This pull request imports the `WithoutModelEvents` trait in seeds, similar to what we do on `RefreshDatabase` in tests.
=> [9.x] Imports without model events trait on seeds

resources/lang/en/validation.php
Comes with https://github.com/laravel/framework/pull/40089
=> [8.x] Add enum translation

resources/lang/en/validation.php
added the validation message to invalid mac_address. 🕵🏻‍♂️
=> [8.x] Add mac_address validation message

composer.json
See https://github.com/fruitcake/laravel-cors/pull/540
=> [9.x] Use latest version of laravel-cors

composer.json
This makes it the new minimum with Laravel v9 support
=> Bump sanctum and tinker versions

composer.json
This is the only change needed to get a beautiful Laravel specific error page whenever an exception occurs.
🌞
🌚
.
=> [9.x] Add Ignition

composer.json
=> Revert "[9.x] Add Ignition"

database/factories/UserFactory.php
Allows PHPStorm to infer the type from the factory class
=> [9.x] Add type to UserFactory for generic parent class

config/session.php
=> [9.x]: remove redundant argument `null` since default is `null`

composer.json
See https://github.com/laravel/docs/blob/9.x/upgrade.md?plain=1#L49
=> Align min PHP version with docs

app/Http/Kernel.php, composer.json
This PR preps the master branch of skeleton for Laravel 10 by removing blocking dependencies. ~I'll create develop branches of Sanctum, Tinker and Sail soon to re-add these.﻿~
=> [10.x] Prep Laravel 10

config/app.php
=> Revert "[9.x] Add Redis facade as comment in app.php config file"

config/filesystems.php
Setup is a noun; Set up is the verb.
=> Small typo fix in filesystems.php

config/cache.php
This comment threw me off today when I was reviewing our config files. Not sure if this text update is exactly what you'd be after but wanted to PR it regardless.
=> The comment for cache key prefix needed an update

config/database.php
Linked to https://github.com/laravel/framework/pull/41683/commits
=> [9.x] Add username in config to use with phpredis + ACL

server.php
Laravel 8 equivalent for https://github.com/laravel/framework/pull/41933
=> [8.x] Fix empty paths for server.php 

config/app.php
[#40102](https://github.com/laravel/framework/pull/40102)
=>  [9.x] Add missing maintenance to config

config/logging.php
Goes hand in hand with https://github.com/laravel/framework/pull/42235
=> [9.x] Deprecation log stack trace option

database/seeders/DatabaseSeeder.php
The very first thing I do when creating a new Laravel app is to setup a specific test user with test credentials that I can use to login without having to register first. I thought to give it a go to not have to do this manually anymore each time. Tried to use a generic as possible name and email address.
=> [9.x] Add specific test user in seeder

.gitattributes, .gitignore, app/Models/User.php, app/Providers/AuthServiceProvider.php, composer.json, database/seeders/DatabaseSeeder.php, tests/Feature/ExampleTest.php
This pull request makes `laravel/pint` a dev-dependency of every Laravel project, while keeping StyleCi to automatically style every new pull request in this skeleton.
=> [9.x] Uses `laravel/pint` for styling

resources/views/welcome.blade.php
Seeing the non compliance of Google Fonts to GDPR I thought to update the CDN.
My non-designer eyes could see no difference on the site.
=> Update font delivery

composer.json, database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
[laravel/sanctum release v3.0.0](https://github.com/laravel/sanctum/releases/tag/v3.0.0)
=> [9.x] Update laravel/sanctum version

composer.json
Alternative for https://github.com/laravel/jetstream/pull/1103
=> Allow Pest plugin in Composer

README.md
added required alt tag to laravel logo image
=> Add alt tag to laravel logo image

lang/en/validation.php
=> [9.x] feature: `max_digits` and `min_digits` validation translations

README.md
Same as https://github.com/laravel/.github/pull/7
=> Add Laravel Bootcamp to Learning Laravel

package.json
I don't see any breaking change
https://github.com/axios/axios/releases/tag/v1.0.0
=> Upgrade axios to v1.x

lang/en/validation.php
See: https://github.com/laravel/framework/pull/44883
=> Adds lowercase validation rule translation

lang/en/validation.php
See: https://github.com/laravel/framework/pull/44918
=> Adds uppercase validation rule translation

.gitattributes
This change is regarding the discussion **[here](https://github.com/laravel/pint/issues/134)**
=> [10.x] Updated git configuration to use LF line endings by default

package.json, resources/js/bootstrap.js
I know this has been attempted many times in the past, but I think the time has come (especially now that we have first party starter kits)
Previous PRs:
https://github.com/laravel/laravel/pull/5466
https://github.com/laravel/laravel/pull/5545
https://github.com/laravel/laravel/pull/3925
=> [10.x] Remove lodash

composer.json
Clean composer.json :
Remove  "dev-master": "10.x-dev"
=> Remove branch-alias from composer.json

config/mail.php
=> Missing comma

config/mail.php
=> Revert "[10.x] add ses-v2 mailer in config"

.gitignore
=> [10.x] Update .gitignore

config/mail.php
Add config for mail url. See https://github.com/laravel/framework/pull/46964
=> [10.x] Add url support for mail config

app/Models/User.php
This pull request makes L11 pass at level max with Larastan. 
```
➜ ./vendor/bin/phpstan
Note: Using configuration file /Users/nunomaduro/Work/Code/l11/phpstan.neon.
3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
[OK] No errors                                                                 
```
=> [slim-skeleton-11.x] Improves type checking on `User::casts`

config/sanctum.php
This PR updates sanctum config file side by side with [sanctum config file](https://github.com/laravel/sanctum/blob/3.x/config/sanctum.php)
=> [10.x] Update sanctum config file

composer.json
This pull request can be merged after this one: https://github.com/laravel/tinker/pull/169.
=> [11.x] Re-adds tinker

composer.json
~Waiting for the release of Laravel Sail `v1.26.0`~
Laravel Sail `v1.26.0` has been released
=> [11.x] Set new Sail constraint

config/database.php
=> Revert "[10.x] Let database handle default collation"

package.json
see [Axios Cross-Site Request Forgery Vulnerability](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)
=> Update axios to latest version

config/session.php
New `partitioned`config key in `session.php`  if https://github.com/laravel/framework/pull/48745 gets accepted.
This would further result in modifications of https://github.com/laravel/framework/pull/47309.
=> [10.x] Add partitioned cookie config key

phpunit.xml
=> Revert "[11.x] Fixes tests failing due database not available"

config/mail.php
In this PR, I'm adding the 'roundrobin' Mail transport driver config which was added in this PR: https://github.com/laravel/framework/pull/49435
=> [10.x] Add roundrobin transport driver config

composer.json
Related to: https://github.com/laravel/framework/pull/49784.
=> [11.x] Requires Guzzle on `laravel/framework`

bootstrap/app.php
Companion PR: https://github.com/laravel/framework/pull/50073.
=> [11.x] Moves `withProviders` to configure method

CHANGELOG.md, composer.json
Depends on https://github.com/laravel/framework/pull/50406
=> [12.x] Prep Laravel v12

composer.json
=> [11.x] Fixes SQLite driver missing

composer.json
Cleans up composer.json similar to https://github.com/laravel/laravel/pull/6103.
=> [11.x] Remove branch alias from composer.json

resources/views/welcome.blade.php
Fix the card of the Vibrant Ecosystem when the mouse hovers over the card
Before
https://github.com/laravel/laravel/assets/46572405/d0aa2e31-88e2-4bbf-90bb-21d706c10011
After
https://github.com/laravel/laravel/assets/46572405/77744553-85a9-4ccb-a269-8ce896772072
=> [11.x] Fix on hover animation and ring

composer.json
Everythings works with no changes needed.
See:
* https://phpunit.de/announcements/phpunit-11.html
* https://github.com/sebastianbergmann/phpunit/blob/11.0.0/ChangeLog-11.0.md
=> [11.x] Use PHPUnit v11

.gitignore
Laravel Herd adds this file when opening up Tinkerwell from Herd
=> Add .phpactor.json to .gitignore

.gitignore
This PR adds Zed editor in the `.gitignore` files
=> Update .gitignore with Zed Editor

.github/workflows/issues.yml, .github/workflows/pull-requests.yml, .github/workflows/update-changelog.yml
Test Action starts with a capital letter, while the others don't, so I changed them for better consistency.
=> Inconsistency in Github action names

package.json
security issue https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6
=> Update vite dependencies

config/session.php
See https://github.com/laravel/framework/blob/066b740f14461bb1a793ebb9742321ee00974060/config/session.php#L35
=> [11.x] Sync `session.lifetime` configuration

composer.json
This feels as a leftover from the dev branch. But if I'm wrong, feel free to close this PR.
=> [12.x] prefer stable stability

resources/css/app.css
Following the same pattern for all `@source` which improves uniformity.
=> Improves clarity in app.css file

package.json
security issue https://github.com/axios/axios/security/advisories/GHSA-jr5f-v2jv-69x6
=> Bump axios from 1.7.9 to 1.8.2 - Vulnerability patch

config/mail.php
**Description:**
The `config/mail.php` file in the project was outdated compared to the core's `mail.php`. This update ensures it remains up to date with the latest changes, including any new options or improvements added to the framework.
=> [12.x] Update `config/mail.php` to match the latest core configuration

README.md
This PR updates the ReadME Partners to better reflect the updated Laravel Partners website and an updated request by Redberry for a new URL.
=> Partner Directory Changes in ReadME

config/services.php
=> fix alphabetical order

config/cache.php, config/database.php, config/session.php
As requested: https://github.com/laravel/laravel/pull/6635#issuecomment-3009111736
=> Change to hyphenate prefixes and cookie names

package.json
This PR addresses a **critical vulnerability** reported by Snyk in the `form-data` package, which is a transitive dependency of `axios@1.10.0.`
> **Vulnerability**: [Predictable Value Range from Previous Values (CVE-2025-7783)](https://security.snyk.io/vuln/SNYK-JS-FORMDATA-10841150)
> **Severity**: Critical (CVSS 9.4)
> **Introduced** via:` axios@1.10.0 > form-data@4.0.0`
> **Remediation**: Upgrade `form-data` to `4.0.4` or higher.
This vulnerability stems from `form-data's` use of `Math.random()` for HTTP multipart boundary generation, which allows for predictability and potential exploitation via parameter pollution attacks.
- Ensured form-data is updated to ^4.0.4, which includes the upstream fix.
- Reviewed dependency tree to confirm no remaining vulnerable paths.
- Confirmed with …
=> Fix Critical Security Vulnerability in form-data Dependency

composer.json
See
---
https://github.com/laravel/pint/commit/0345f3b05f136801af8c339f9d16ef29e6b4df8a
=> [12.x] Bump Pint version

package.json
These are the two CVEs affeting vite
https://github.com/vitejs/vite/security/advisories/GHSA-g4jq-h2w9-997c
https://github.com/vitejs/vite/security/advisories/GHSA-jqfw-vq24-v9c3
\>=7.0.0,<=7.0.6
=> Fix CVEs affecting vite
